Cataclysm-TLG/Cataclysm-TLG

data/json/items/armor/legs_armor.json, data/json/professions.json
Give mask cartridges to firefighters and fix plastic leg guards
Firefighters couldn't use the masks they started with, and plastic leg guards were offering arm protection for some reason.
- Give filters and remove jiu jitsu (nonexistent) from a few professions.
- Remove duplicate firefighter profession
=> Fix plastic leg guards and three professions

src/armor_layers.cpp, src/item.cpp, src/item.h, tests/coverage_test.cpp, tests/iteminfo_test.cpp
Currently protection/coverage stats are not displayed in 'sort armor screen' and 'body status screen'.
I thought this would fix a bug I was working on, but it didn't. Alas.
Straightforward backport, making sure we keep adjusted_coverage in item.cpp
Compiles, runs, looks fine.
=> Backport DDA 62126 - Fix displaying of stats for ablative armor

data/json/items/armor/arms_armor.json, data/json/items/armor/boots.json, data/json/items/armor/gloves.json, data/json/items/armor/legs_armor.json, data/json/items/armor/suits_protection.json, data/json/items/armor/torso_armor.json, data/json/materials.json, data/json/recipes/armor/suit.json
Continue auditing armor and ensuring suits and separates match warmth/enc/coverage/etc
Platemail, leather, chitin, and chainmail armor exist as separates, but for convenience or a few other purposes, can be combined into sets represented by a single item. There were a few little errors in this process, mismatched encumbrance values and the like.
Platemail tassets and leg guards weren't quite right, coverage wise.
The Faraday sets are more or less the same thing but incorporate a cleansuit, so I also wanted to ensure the values were roughly equivalent to combining a cleansuit with the set in question.
Lastly, full plate wasn't craftable. I added a recipe which just involves putting the whole set together.
Manually compare and adjust encumbrance values for
- Chain
- Plate
- Brigandine
- …
=> Metal Armor fix-ups

msvc-object_creator/ObjectCreator-vcpkg-static.vcxproj
Change a DDA reference in msvc build workflow to TLG
make it go
do it
=> Fix windows build action maybe

msvc-object_creator/vcpkg.json
More windows build stuff! This coulda all been one PR really.
=> Backport DDA 79360 - Fix a build error with the object creator

data/json/items/armor/boots.json
Fix typo in boots_western description and adjust encumberance
Fix for boots_western, refs https://github.com/Cataclysm-TLG/Cataclysm-TLG/issues/395
Fixed the typo and adjusted the encumberance to what DDA uses :)
=> Fix typo in boots_western and adjust encumberance

data/mods/Sky_Island/upgrade_missions.json
Changed fp_loyalty_card to loyalty_card, allowing this recipe to be crafted and not run an error. Tested in my game. Fixes https://github.com/Cataclysm-TLG/Cataclysm-TLG/issues/399 . Apologies if I have bumbled the formatting or something here, first time using Github.
Fixes small error.
Changed fp_loyalty_card to loyalty_card , as it's the same thing as the old (removed?) 'Foodperson's Loyalty Card' that the recipe was referring to, and spawns in wallets like the rest of the items in the recipe.
Changing it to a score card or a cash card, leaving it broken
Booted up on my PC with the change in effect, no issues. Have not tested with a world that has been running Sky Island, however.
Recipe now calls for a normal item and doesn't run an error on startup. Again, apologies if I've messed up …
=> Update upgrade_missions.json to fix error with Sky Island

data/json/mapgen/map_extras/specimen_van.json
Reduce damage to specimen van map extra
The specimen van accidentally had its condition set to 1 (heavily damaged) instead of -1 (lightly damaged). This meant the player was unlikely to be able to recover any of the intended goodies from inside.
Delete the "condition": object, as it defaults to -1.
The game loads but there's no way to spawn map extras. I looked around a bit but I can't be assed to find one so I'll just wait for a player to find one and ask them how it went. I'm not working hard, I'm working smrat.
=> Reduce damage to specimen van map extra

data/json/effects.json, data/json/mutations/mutation_category.json
Make untyped mutagen cause random mutations.
#37 got rid of the primer/catalyst system. The intent was that untyped mutagen would cause random mutations, but it didn't work because from_mutagen() in suffer.cpp was set up to look for typed mutagen.
Apply the untyped mutagen effect to the "All" mutation category. Now untyped mutagen picks fully random mutations.
Note that typed mutagens have a small amount of untyped mutagen in them. If you take too much, you'll start getting random mutations that you might not want...or you might be pleasantly surprised. If you'd like to ensure that you ONLY get the mutations from your line, use typed infusions instead, which lack untyped mutagen.
Loaded in, drank untyped mutagen. Became disease resistant and grew rabbit ears. Not bad.
=> Make Untyped Mutagen Work

data/json/monsters/insect_spider.json, src/monster.cpp
Make ACIDPROOF monsters immune to acid effects.
Ensure that monsters intended to be acidproof (mostly those who spit acid) are unable to be killed by their own puddles.
- Ensure that the oversized acidic ant has the ACIDPROOF flag
- Ensure that ACIDPROOF grants monsters immunity to the corroding effect
Spawned some acid ants and watched them not die in their own acid.
Previously, acid armor incidentally made monsters resistant to acid puddles. That is no longer the case. That needs a fix, but not this instant.
=> Acidic monsters are acidproof

data/json/items/armor/cloaks.json
Add a small amount of encumbance to ponchos that lacked it
The rain poncho didn't have any encumbrance, but most other cloak-type items did.
The rain and makeshift ponchos were given a small amount of encumbrance.
=> Add encumbrance to ponchos

data/json/overmap/overmap_special/specials.json
Nudge overmap settings to reduce apple orchard spam
Apple orchards can spawn as part of mutable farms, so we don't ALSO need 5 freestanding apple orchards per overmap (at maximum).
Reduced the max number of freestanding orchards to 3, nudged a few other things that were especially common.
Three orchrds on this entire overmap. Not too bad.
This is gonna be one of those forever projects.
=> Nudge overmap settings

data/json/items/armor/cloaks.json, data/json/mapgen/mansion.json
Fix mansion clutter probability
fixes #386 
DDA changed the default probability for item placement in mapgen from 1% to 100%. So mansions were carpeted in trash that was supposed to be very infrequent.
Manually set 1 probaility.
=> fix mansion trash

data/json/items/armor/legs_clothes.json, data/json/items/armor/swimming.json, data/mods/innawood/recipes/armor/head.json, data/mods/innawood/recipes/armor/storage.json, data/mods/innawood/recipes/armor/torso.json, data/mods/innawood/recipes/weapon/ranged.json
Fix most encumbrance issues with pants.
DDA has, to my knowledge, SIX methods for determining encumbrance:
1) A single encumbrance value per "covers": entry in the armor definition.
2) volume_encumbrance_modifier, which attempts to automatically determine extra encumbrance from pocket fullness.
3) A bracketed pair of encumbrance values, min and max, which do the same as the above.
4) Proportional encumbrance, used in copy-from.
5) Flag-based encumbrance, used for helmets.
6) Extra_encumbrance, defined on individual pockets.
This is all layered overtop of the VARSIZE, OVERSIZE, and UNDERSIZE flags, and it just sucks so bad. All we need is 1 ,3, and 6. All other methods are to be phased out. 
There is a bug with method 3: if multiple sub-bodyparts are defined and one of them has paired …
=> Fix Pants Encumbrance

Makefile
Backport DDA 77413 - Include freetype2 library when compiling on MacOS
=> Backport DDA 77413 - Include freetype2 library when compiling on MacOS

data/json/items/armor/bespoke_armor/custom_headgear.json, data/json/items/armor/helmets.json
Fix encumbrance for most headwear, coverage for survivor hoods
fixes #419 
A bunch of helmets had their encumbrance set up wrong (see #421 ). This fixes most of them. It also moves survivor hoods to the BELTED layer as intended (all such hoods should go there) and fixes their body parts and encumbrance.
Plate helmets now offer around 30 head encumbrance. Modern armor helmets with lower coverage are less than that, some are more. This may seem high, but remember that head encumbrance doesn't matter aaaall that much, and that the helmet is generally the only thing you're wearing up top, unless you're matching it with a hood or some kind of skintight piece.
I surely missed a few, but oh well.
Loaded, ran, spawned in several helmets, looked at all of them, they seem fine.
=> Draft: Headwear Fixes

data/mods/innawood/items/misc.json, data/mods/innawood/recipes/recipe_food.json
Adjust slow-sand water filter to use innawood materials
The water filtration system added to DDA was causing problems for innawood.
Switch from a bucket to a clay hydria. Change the material of the filter to clay.
Saw the filter in the construction menu with the proper ingredients, spawned the item and it looks as intended.
=> Innawood water filter

data/json/items/armor/storage.json
Move the transformed messenger bag from OUTER to OVERTOP
Fixes a DDA bug where an adjusted messenger bag was fitting on the wrong layer. This was making it conflict with a lot of clothing and armor.
Outer->overtop
=> Messenger Bag Fix

src/activity_handlers.cpp
Characters with the Psychopath trait don't get a penalty, those without do.
Fixes #392 "Psychopath receiving morale penalties for dissection." 
Changed the logic.
None
Tried butchering and dissecting a zombie and an unfortunate starting NPC on a fresh character with the Psychopath trait.
=> No popup, no morale penalty.
Debug-removed Psychopath trait and tried the same.
=> Popups for NPC, no popup for the zombie. Got sad dissecting the NPC, as expected.
None
=> Fix Psychopath butchery/dissection morale penalty

build-data/osx/Cataclysm.sh
The included libz is unreadable by macOS <10.15. In that case, we can replace it with a built-in copy.
Let CTLG run on macOS 10.14 (and probably 10.13 because that's the compilation target, but I haven't checked).
When launching CTLG for the first time, replace the included libz with a copy included in the OS. Then, write a sigil file so the replacement is only done once. 
It's theoretically possible that CTLG could directly use the OS copy of libz. I think this would make the process of building for macOS significantly different from other targets and generally seems like an avoidable can of worms.
Launched the game using the script from different states (including bad/missing libz) and made sure the sigil file prevents repeat copying.
=> Replace libz with built-in copy on macOS <10.15

data/json/items/armor/torso_armor.json
Fix riot guard encumbrance and description
The riot guard's encumbrance was set incorrectly. Its description also didn't make it super clear what it is.
Update the description and bring encumbrance in line with riot armor
=> Update Riot Guard Encumbrance and Description

src/worldfactory.cpp
Backport DDA 74486 to fix android build
STD::timespec doesn't exist in Android NDK's standard library. This backport from DDA switches to a different function.
=> Backport 74486 - Fix android build

data/json/itemgroups/supplies.json, data/json/mapgen/basement/basement_bionic.json
Fix rubber sealant spray cans being empty all the time.
They were empty
Fill them
=> Rubber spray fix

src/map.cpp
Backport DDA 75453 - Prevent negative array index for floor_cache
Probably fixes #441 
A simple backport.
Loaded the game, loaded the save in #441, looked over in that direction, got no crash.
=> Backport 75453 - Prevent negative array index for floor_cache

data/json/items/armor/legs_clothes.json, data/json/professions.json, data/json/recipes/armor/legs.json, src/profession.cpp
Backport DDA 74649 - Vegan profession item substitutions, plus additions
fixes #440 
This was a desired PR for backport but it got bumped up because of a request.
Backports the PR, adds a recipe for making the utility kilt, makes it out of canvas instead of cotton (really now!), brings its encumbrance in line with the other skirt-type items, updates said items, and assigns a few vegan substitutions for common profession items.
Subs in our slip-on shoes for DDA's espadrilles.
We need more substitutions defined but that's another PR.
Loads, can play as vegan razorgirl.
Vegan Razorgirl
=> Backport DDA 74649 - Vegan profession item substitutions

src/character.cpp
Fix one more grappling-related crash
It was still possible to crash the game while grappling if you turbo mashed the attack button.
Move the nullptr/is_dead_state() check to the top of Character::process_turn() so that orphan grabs are cleared before anything else happens, no matter how fast you button mash.
Getting into hard drugs
Grappled things a lot and killed them and experienced no crashes or orphan grabs.
There are probably still ways to get crashes and orphan grabs. They'll be fixed as we go.
=> MA update addendum

android/app/src/main/java/com/cleverraven/cataclysmdda/CataclysmTLG.java, android/app/src/main/java/com/cleverraven/cataclysmdda/CataclysmTLG_Helpers.java, android/app/src/main/java/com/cleverraven/cataclysmdda/NativeUI.java, android/app/src/main/java/com/cleverraven/cataclysmdda/SplashScreen.java
Clean up some references to DDA in Android build files
The Android build files still reference DDA
I think we can just DDA -> TLG these.
That's the neat part.
=> Fix some android stuff maybe

data/json/monstergroups/zombie_upgrades.json, data/json/monstergroups/zombies.json, data/json/monsters/zed_burned.json, data/json/monsters/zed_electric.json
Give shocker zombies a short lifespan and make them very rare
Shockers are really oppressive enemies that are super cool, but ruined by their ubiquity. Rather than being an odd surprise, they're constant, pushing players to want to always have shockproof gear. That's not ideal!
- Shockers are about 1/20th as common as they were in the general zombie pools.
- Shockers have a short lifespan, generally becoming scorched zombies (or fiends) within about a week.
- Shocker brutes etc. still exist, and also have short lifespans.
- Zaptors are less common, but don't have a shortened lifespan because they're already part of another monster's lifespan and there wasn't a burned variant so I don't care that much.
- Shockers still show up at more or less the same rate in power plants and other …
=> Reduce incidence and lifespan of shockers

src/magic.cpp, src/magic.h, src/magic_spell_effect.cpp
Backport 76969 - fix spells segfaulting from wrong creature
The game was crashing when monsters cast damaging spells.
Backport stops assuming spells only come from characters.
Compiles, runs, bombardier boomers and phase shrikes no longer crash the game.
=> Backport 76969 - fix spells segfaulting from wrong creature

src/monmove.cpp
Randomize, rather than alphabetize, the enemy attack list when picking a valid attack.
Fixes an issue where enemies will always pick first attack in the list, which is always in alphabetical order causing enemies to always use same attack when possible f.e zombie always trying to grab player instead of trying to scratch them.
see: https://github.com/CleverRaven/Cataclysm-DDA/issues/75659
Instead of iterating attacks list from the start, now it doesn't make it fully random, but just offsets attacks list by random number to start iterating from different attack (bite, grab, scratch) -> (scratch, bite, grab).
Original PR at #455 - moved here (preserving authorship) because it was faster to make changes than ask for corrections.
Compiled, ran, juggernaut attacks randomly instead of spamming …
=> Fix enemy attack order

src/debug_menu.cpp
Debug mx spawn tinymap -> smallmap
Backport 74754 fix to debug location spawns
Backport manually (for some reason the script isn't working) with attribution in commit comment.
=> Borrow 74754 fix

doc/CONTRIBUTING.md
Change Contributing documentation such that the hyper link forks TLG not CDDA
Prevent unfortunate future contributors from forking the wrong thing and getting confused.
change the hyperlink text
n/a
ctrl clicking the hyperlink
=> Update fork link

src/activity_handlers.cpp, src/character.cpp, src/explosion.cpp, src/ranged.cpp
Grenades are deadlier but more variable, improved crouch/prone behavior
fixes #459 
Grenades were undertuned, being way too safe to be near and not effective enough on monsters.
- Rework the shrapnel calculations, reducing the likelihood that no shrapnel will hit a target, and allowing targets to be hit by more shrapnel than was previously possible. It's now also more likely that instead of taking minimal damage or getting whammied, you'll get something in between, especially if you armor up.
- Reduce the effectiveness of crouching and going prone. Previously they were 0.6 and 0.25 stance_factor, now they're 0.75 and 0.5. Going prone is still very effective, but not foolproof.
- Ensure that characters who have the lying_down or downed effects are given the benefit of stance_factor.
- …
=> Deadlier but more variable grenades

data/json/regional_map_settings.json, src/trapfunc.cpp
Reduce the number of mined bridges and make land mines hit a wider area
Land mines were only affecting a 3x3 area and basically had no shrapnel to speak of. They were also way too common.
- Adjust the casing size and power of land mines so that they function like weaker hand grenades
- Reduce incidence of mined bridges by 30%, as it was reported they were too common.
Land mines deal 90 to 140 damage to a zombie that steps on them. It's basically always a kill on a basic zom, and almost always on an unarmored survivor. What can I say: Don't step on land mines.
They can kill adjacent zombies too, but they're not excellent at it. This reflects IRL land mines, which are meant to wound and terrorize rather than simply evaporate all combatants.
During one test I got an unlucky hit from some …
=> beef up mines but make them rarer

data/json/effects_on_condition/bionic_eocs.json, data/json/enchantments.json
Fix some issues with bionic faults
Bionic ankles were mistakenly quadrupling step sound instead of doubling it, resulting in some preposterous stomps. Bionic noisemaker was as loud as a gunshot, and leaky bionic was reducing health to -200 in like a day or two.
- Bionic noisemaker now makes sound at volume 40. This is louder than a typical person's shout, but not gunshot-loud.
- Bionic ankles now double instead of quadrupling step sound.
- Leaky bionic triggers 1/2 as often and now only has a 50% rather than a 100% chance to reduce lifestyle. This will still make you unable to naturally heal within a couple of days (especially combined with the radiation you're getting from the other bionic). The idea is that you have about a week to get this crap out of you before it bricks your run.
- I …
=> Fix some issues with bionic faults

Makefile
Fixes #468 
The macro def flag `-DDATA_DIR_PREFIX` was replaced with `-tlgTA_DIR_PREFIX`. The DDA in this flag is not the name of the game.
Change it back. I checked the rest of the repo for `-tlg`, this is the only sus occurrence.
Forking the compiler to recognize -tlg as a macro def that starts with DA.
@Reledia said it works.
=> Fix incorrect dda->tlg in macro def

data/xdg/com.cataclysmtlg.CataclysmTLG.appdata.xml, data/xdg/com.cataclysmtlg.CataclysmTLG.desktop
Fix some incorrect xdg filenames
Some xdg files were pointing to incorrect filenames. This fixes them to be consistent.
cataclysmtlg->cataclysm-tlg
=> Fix some incorrect xdg filenames

data/json/hobbies.json, data/json/professions.json
Minor chargen fixes
8 point professions were too expensive to actually play in multipool. Fire performer had high adrenaline which wasn't working because it's thresh-locked to beast and chimera.
- Remove adrenaline from fire performer, get rid of its 1 survival and give it 1 dodge and throwing.
- Reduce the point costs for several professions. 7 is now to be considered the cap. Downshift a few starting skill levels.
- Reduce point costs for a few other starting professions.
- Hobbies and professions need to be gutted. They should mostly be for getting proficiencies and starting gear, aside from the mutant starts which need professions for that.
- Hobbies and professions should work out their costs differently for multipool. Maybe they should list x/y/z and then there should be some math …
=> Minor chargen fixes

src/activity_handlers.cpp, src/inventory_ui.cpp, src/inventory_ui.h
Fixes a bug where you can try to use firestarter object as a tinder making you fail to start fire, cause firestarter is moved to fireplace position.
Bug fix.
After collecting all possible tinder options RemoveItem is run and compare to all possible options we got to the firestarter item and if items pointers are the same(items point to the same object in memory) item is removed from possible tinder list.
Due to the way the code is structured, it's the simplest solution I could think of.
Tested with 2 matchboxes, one is empty and other is full with no other option to start fire. Before fix both showed up and on trying to start fire with full matchbox we failed to start fire. After fix only empty showed up.
=> Firestarting bug fix

src/melee.cpp
Fix segfault from bad combat message indexing
#472 slightly changed the combat messaging in melee.cpp and I messed up the indexing on the combat messages (ie you clobber X for 72 damage!). This led to some segfaults if you did a lot of damage.
Fix the index, add a message to make it easier to keep track of.
Tried a few different weapons, no segfaults.
=> Fix segfault from bad combat message indexing

data/json/items/armor/storage.json
Make messenger bag swappable when worn on hip
Did you know you can activate the messenger bag to wear it at your side rather than on your back? You've always been able to, except it sort of didn't work right. The bag was laying over both legs, and its swap sides mechanic wasn't working. This was because swappable items can only go on one sub-bodypart. While that's an issue that deserves its own fix, this is easy enough to remedy here.
Make the messenger bag just go on the hip, not the hip and leg_upper. It can now be worn on either side.
=> Make messenger bag swappable when worn on hip

data/json/monsters/insect_spider.json
Curb preposterous armor penetration on insect attacks
Insects for some reason get to have a ton of armor penetration on their attacks, a power no other enemy type enjoys. This is unacceptable and it's weird that it's just this one enemy type. The giant wasp queen had 60 arpen on her sting and the armored centipede had ONE HUNDRED AND TEN on its bite. This is the epitome of lasagna design - layering a new mechanic over old unfixed systems that totally obviates them is not the way to go about things.
Drop everything to like 10-20 tops. I don't really want one enemy type to have all this bespoke arpen when nobody else gets it, but it's not totally unreasonable for certain kinds of attacks - the player gets tons of arpen and nobody complains about that.
As a simple fix, for now I'll leave it …
=> Curb preposterous armor penetration on insect attacks

data/json/furniture_and_terrain/terrain-walls.json, data/json/mapgen/bugs/beehive.json, data/json/mapgen/mi-go/mi-go_nested.json, data/json/npcs/classes.json, data/json/npcs/factions.json, data/json/npcs/npc.json, data/json/overmap/overmap_special/specials.json
Remove the NPC named Apis
Apis was always very weird. The source of a ton of bugs (people constantly disarming its bodyparts, or wondering why there was one in every beehive, or noticing them in mi-go towers) and never really had any story or anything. A long time ago, there was some indication that scientists had been messing with the giant bees, but that's all gone now.
We want mutant NPCs, but Apis was just a random bad guy with no loot. Meh.
Delete
Compiled and ran, no warnings. Found a beehive, no Apis.
=> Remove Apis

data/json/effects_on_condition/mutation_eocs/changing_eocs.json, src/mutation.cpp
Fix debug menu mutation
#485 broke debug menu mutations by making the ANY category require vitamins.
- Slip in an exemption for debug stuff.
- Remove reference to "nutrients" in some mutagen messaging. Mutagen is NOT nutrients.
Mutated all the ways I could think of, purified, saw costs were appropriate at all times.
=> Fix debug mutation

src/character.cpp, src/character.h, src/npcmove.cpp, src/ranged.cpp
Improve NPC weapon selection
NPCs have a long, long way to go. I want them to act like RPG party members. They're still a bit squirrely for that, but we can make a start of it here.
Somebody caught one trying to wield integrated weapons. I looked into this and saw that they were totally indiscriminate in selecting melee weapons, which was leading to the ancient and entirely stupid behavior of taking their armor off to hit you with it.
- Worn and integrated items are no longer considered valid choices for melee or thrown weapons by NPCs.
- Moved the dispersion RNG to a standardized function, added another function that gets the average of whatever your RNG roll would be, and added that to the NPC's aim confidence calculation. I'm not 1000% sure this is working as intended, but it seemed to …
=> Improve NPC weapon selection

data/json/recipes/armor/arms.json, data/json/recipes/armor/torso.json
Added/Updated armor recipes
Leather Pauldrons are a requirement for crafting the leather armor suit, but didnt have a recipe
Hoodies require 40 sheets or approximately 69sqft (nice) of material
Readded recipe for Leather Pauldrons. Based on leather vambraces as per Wormgirl
Lowered sheet requirement from 40/20 sheets to 6 or 12sqft
=> Recipe Tweaks

data/json/items/armor/suits_protection.json
Fix riot armor foot coverage
Riot armor has boot covers that were conflicting with other gear. This issue was not present in the riot leg guards, which are a component of riot armor.
Give the foot part of riot armor the BELTED flag so it fits where it's supposed to. Now you can wear it with most shoes!
Look at that, sneakers and all.
You people are OBSESSED with riot armor.
=> Fix riot armor foot coverage

src/map_selector.cpp, src/mapgen.cpp, src/mapgen_functions.cpp, src/rng.h
Backport DDA 74732 - map rotation fix
Some lab and lab-adjacent maps weren't properly rotating following a recent backport.
=> Backport 74732 - map rotation fix

src/cata_tiles.cpp
Backport DDA 74617 - Only get valid rotations for SDL overmaps
Attempt to fix an issue reported on Discord
=> Backport DDA 74617 - Only get valid rotations for SDL overmaps

data/json/items/melee/bludgeons.json, data/json/monsters/mammal.json
Nerf chain whip, fix dog weight
Attack dogs had the wrong weight, chain whips were a bit too strong. The chain whip should be kind of a bad weapon that does a unique thing, which is bash damage that has a reach attack and no range penalty.
Make the whip heavier and reduce its damage by 2.
Fix Dog Weight
The whip should probably have a special attack that just takes longer or something, so it's a bit harder to kite with.
Whip looks better, dog can wear armor.
=> Nerf chain whip, fix dog

data/json/enchantments.json, src/character.cpp
Electronic night vision overrides biological
NVGs were way too powerful because the game was totaling up all sources of night vision. This does not reflect how these devices work in real life - NVGs use an electronic system to intensift visible spectra and/or convert non-visible spectra into visible wavelengths. In effect, the user is watching a camera feed, and not actually looking directly at the subject - even if that wasn't true, the NVGs are only "illuminating" the same areas which animalistic night vision would be able to see, there's no reason the two should stack additively, to say nothing of whether an electronic screen designed for humans would even be visible to an animal's eyes.
Mutation-related NV remains the same. However, if you are using bionic or item-based NV, your new …
=> Electronic night vision overrides biological

data/json/effects.json, src/character.cpp, src/character_attire.cpp, src/player_hardcoded_effects.cpp
Remove infinite onfire and reduce fire damage
Fire had a major problem: Any time you took fire damage on a body part, it would check to see if your clothes ignited there. If they did, it would add to that body part's onfire duration. Onfire deals fire damage to body parts, so this would result in you getting more stacks of onfire than you could put out.
Fire has many other issues - you also get burned by hot air AND hurt by the blisters that come from being burned by the hot air, AND slowed down by the effects and the pain, etc. so we also need to reduce the damage overall. Throwing a molotov at an adjacent enemy should be a tremendously stupid thing to do, but enemies need to be able to use fire without invariably killing the player.
So:
- Clothes damaged by fire would always apply …
=> Fire is no longer invariably fatal

data/json/npcs/your_followers/luo_follower.json
Give Luo a switch-to option in her dialog
Luo (the mycologist at the refugee center) is recruitable, and has her own version of the regular ally dialog. I forgot to give her an option to switch like everyone else got in #528 
copy paste
=> Give Luo a switch-to option in her dialog

src/vehicle.cpp, src/vehicle.h
Backport DDA 74964 - Stop appliances/power grids from turning off when reloading
When you leave an area with a power grid and come back, the active appliances will check their power grid to see if they had power enough to continue running. If the batteries and whatnot are not in the reality bubble when that happens, they erroneously turn off. This PR fixes that issue.
=> Backport DDA 74964 - Stop appliances/power grids from turning off when reloading

data/json/mapgen/bike_shop.json, data/json/mapgen/butcher.json, data/json/mapgen/hunting_lodge.json, data/json/mapgen/irradiator_1.json, data/json/mapgen/nested/farm_nested.json, data/json/mapgen/nested/lodge_nested.json, data/json/mapgen/restaurant.json, data/json/mapgen/s_lightindustry.json, data/json/mapgen/s_lightindustry_scen.json, data/json/mapgen_palettes/lodge_palette.json, data/json/monsters/turrets.json
Make several locations much less safe
- The irradiation plant, light industry, and hunting lodges were all far too safe, being guaranteed high-value areas often with no monsters at all. I think in the case of the irradiation plant, this may have been due to a bug.
- Glooscap's lodge was set up to sometimes contain cannibal food. I believe this was an error, but it's not appropriate. Glooscap is the greatest hero of the Wabanaki people. Those cultures consider cannibalism to be one of the worst evils a person can commit. It's probable that Glooscap in Cataclysm is just some guy who has lost his marbles, but it'd still be weird for him to be sitting next to a bunch of chopped up human flesh.
- I discovered that the roof backports undid a lot of my GROUP_ROOF_ANIMAL placement, which has been …
=> Make several locations much less safe, farms safer.

data/json/flags.json, data/json/items/comestibles/drink.json, src/active_item_cache.cpp, src/active_item_cache.h, src/flag.cpp, src/flag.h, src/item.cpp, src/item.h, src/item_contents.cpp, src/item_contents.h, src/item_pocket.cpp, src/item_pocket.h, src/map.cpp
Backport 74353 - clean water goes bad if left in open container
Prereq for some coordinate stuff, and also just generally wanted
=> Backport 74353 - clean water goes bad if left in open container

src/active_item_cache.cpp, src/active_item_cache.h, src/coordinate_constants.h, src/coordinates.cpp, src/coordinates.h, src/item.cpp, src/item.h, src/map.cpp, src/map.h, src/savegame.cpp, src/savegame_json.cpp, src/submap.cpp, src/submap.h, src/vehicle.cpp
Backport DDA 74823 - typification stuff
Prereqs for other stuff and a good project in its own right.
Backport. During backporting a comment and no-lint was briefly added to map.cpp and then removed, this comment in the commit history is from DDA 74740 by Maleclypse. That'll be backported next for proper attribution.
=> Backport DDA 74823 -typification stuff

src/map.cpp
Backport DDA 74740 - Silence erroneous clang-tidy warning
I haven't been using clang-tidy but I remember NetSysFire saying I should for some reason, and they're usually right. So I'll just quietly backport this. Note that this code accidentally appeared in #534 (in the commit history) but wasn't merged with it. Backporting it here and linking it there (it's also mentioned in the PR body there) should be sufficient for attribution.
=> Backport DDA 74740 - Silence erroneous clang-tidy warning

src/active_item_cache.cpp, src/active_item_cache.h
Backport dda 74555 - clang-tidy: fix cata-unsequenced-calls
More clang-tidy stuff.
=> Backport dda 74555 - clang-tidy: fix cata-unsequenced-calls

data/json/monsters/zed_command.json, data/mods/Megafauna/monsters/mf_domestic.json, data/mods/Megafauna/monsters/mf_predators.json, data/mods/Megafauna/monsters/mf_wild.json, data/mods/Mythos-Creatures/monsters/mythos.json, data/mods/TEST_DATA/monsters.json
Clean up PATH_AVOID_DANGER_1 flags
Some of the mods and a few random spots still had the PATH_AVOID_DANGER_1 flag.
PATH_AVOID_DANGER_1 -> PATH_AVOID_DANGER
=> Clean up PATH_AVOID_DANGER_1 flags

data/json/monsters/mutant.json
I made chuds afraid of light and forgot to give them cornered_fighter.
=> Pathfinding fixes addendum

src/sdltiles.cpp
Backport DDA 74481 - Fix Mouse Overmap Migration When Using Iso tiles
=> Backport DDA 74481 - Fix Mouse Overmap Migration When Using Iso tiles

build-scripts/get_all_mods.py
Backport DDA 74476 - allow mod exclusions in get_all_mods.py
=> Backport DDA 74476 - allow mod exclusions in get_all_mods.py

src/handle_action.cpp
Backport DDA 74460 - fix typo & refactor
=> Backport DDA 74460 - fix typo & refactor

data/json/itemgroups/books.json, data/json/items/toy.json, data/json/npcs/godco/members/NPC_Sonia_Greene.json, data/json/npcs/godco/members/cook.json, data/json/npcs/militia/GM_Militia_Merchant.json, data/mods/Megafauna/monsters/mf_domestic.json, tools/spell_checker/dictionary.txt
backport DDA 74458 - Fix text typos.
=> backport DDA 74458 - Fix text typos.

data/json/recipes/recipe_medsandchemicals.json
Backport 74450 - Fix calculation error in potassium iodide recipe
=> Backport 74450 - Fix calculation error in potassium iodide recipe

data/mods/Backrooms/game_balance.json, src/map_extras.cpp
Backport DDA 74434 - Indestructible terrain and external mapgen options
=> Backport DDA 74434 - Indestructible terrain and external mapgen options

data/json/items/melee/swords_and_blades.json
Backport DDA 74415 - KA-BAR now looks like National Guard Bayonet
=> Backport DDA 74415 - KA-BAR now looks like National Guard Bayonet

data/json/vehicle_groups.json
Backport DDA 74467 - Remove weird DUKW spawns
=> Backport DDA 74467 - Remove weird DUKW spawns

data/json/recipes/recipe_medsandchemicals.json
Backport 74489 - Phosphorus from Matchboxes and Potassium Chloride From Match-heads
=> Backport 74489 - Phosphorus from Matchboxes and Potassium Chloride From Match-heads

data/raw/keybindings.json, src/avatar.cpp, src/avatar.h, src/character.h, src/character_morale.cpp, src/display.cpp, src/medical_ui.cpp, src/npctalk_funcs.cpp, src/player_display.cpp
Backport 74406 - See NPC morale, edit name/gender etc in @ menu
=> Backport 74406 - See NPC morale, edit name/gender etc in @ menu

data/json/mapgen/basecamps/expansion/modular_storehouse/version_1/modular_storehouse_construction.json, data/json/mapgen/basecamps/expansion/modular_storehouse/version_1/modular_storehouse_palettes.json
Backport DDA 73998 - Explicit roof on storehouse 1
Confusing how this got missed, but it's needed for the next backport.
=> Backport DDA 73998 - Explicit roof on storehouse 1

data/json/techniques.json
Fix precise strike working on zombies
Somehow in the martial arts shuffle, precise strike lost its species exclusions.
- Re-add the exclusions, but be a little more generous. There's no reason it shouldn't work on cyborgs, mi-go, and krakens as those are still living things. Aberrations and stuff I'm leaving on the exclusion list.
- Amend many other MA stun techs to have similar exclusion lists. Generally this makes them a lot more permissive they were.
- Remove the humanoid requirement from most of these. Palm-striking a dog in the face can stun it, why not?
=> Fix precise strike working on zombies

data/json/mapgen/basecamps/expansion/modular_workshop/version_1/modular_workshop_common.json, data/json/mapgen/basecamps/expansion/modular_workshop/version_1/modular_workshop_construction.json, data/json/mapgen/basecamps/expansion/modular_workshop/version_1/modular_workshop_palettes.json
Backport DDA 74037 - Added roofs to workshop 1
=> Backport DDA 74037 - Added roofs to workshop 1

data/json/mapgen/basecamps/expansion/modular_canteen/version_1/modular_canteen_construction.json, data/json/mapgen/basecamps/expansion/modular_canteen/version_1/modular_canteen_palettes.json, data/json/mapgen/basecamps/expansion/modular_canteen/version_2/modular_canteen_construction.json, data/json/mapgen/basecamps/expansion/modular_canteen/version_2/modular_canteen_palettes.json, data/json/mapgen/basecamps/expansion/modular_garage/version_2/modular_garage_construction.json, data/json/mapgen/basecamps/expansion/modular_garage/version_2/modular_garage_palettes.json, data/json/mapgen/basecamps/expansion/modular_livestock/version_1/modular_livestock_construction.json, data/json/mapgen/basecamps/expansion/modular_livestock/version_1/modular_livestock_palettes.json, data/json/mapgen/basecamps/expansion/modular_livestock/version_2/modular_livestock_construction.json, data/json/mapgen/basecamps/expansion/modular_livestock/version_2/modular_livestock_palettes.json, data/json/mapgen/basecamps/expansion/modular_saltworks/version_1/modular_saltworks_construction.json, data/json/mapgen/basecamps/expansion/modular_saltworks/version_1/modular_saltworks_palette.json, data/json/mapgen/basecamps/expansion/modular_storehouse/version_1/modular_storehouse_construction.json, data/json/mapgen/basecamps/expansion/modular_storehouse/version_1/modular_storehouse_palettes.json, data/json/mapgen/basecamps/expansion/modular_storehouse/version_2/modular_storehouse_construction.json, data/json/mapgen/basecamps/expansion/modular_storehouse/version_2/modular_storehouse_palettes.json, data/json/mapgen/basecamps/expansion/modular_workshop/version_1/modular_workshop_construction.json, data/json/mapgen/basecamps/expansion/modular_workshop/version_1/modular_workshop_palettes.json, data/json/mapgen/basecamps/expansion/modular_workshop/version_2/modular_workshop_construction.json, data/json/mapgen/basecamps/expansion/modular_workshop/version_2/modular_workshop_palettes.json, data/json/recipes/basecamps/expansion/recipe_modular_canteen/version_1/recipe_modular_canteen_construction.json, data/json/recipes/basecamps/expansion/recipe_modular_canteen/version_2/recipe_modular_canteen_construction.json, data/json/recipes/basecamps/expansion/recipe_modular_garage/version_2/recipe_modular_garage_construction.json, data/json/recipes/basecamps/expansion/recipe_modular_livestock/version_1/recipe_modular_livestock_construction.json, data/json/recipes/basecamps/expansion/recipe_modular_livestock/version_2/recipe_modular_livestock_construction.json, data/json/recipes/basecamps/expansion/recipe_modular_saltworks/version_1/recipe_modular_saltworks_construction.json, data/json/recipes/basecamps/expansion/recipe_modular_storehouse/version_1/recipe_modular_storehouse_construction.json, data/json/recipes/basecamps/expansion/recipe_modular_storehouse/version_2/recipe_modular_storehouse_construction.json, data/json/recipes/basecamps/expansion/recipe_modular_workshop/version_1/recipe_modular_workshop_construction.json, data/json/recipes/basecamps/expansion/recipe_modular_workshop/version_2/recipe_modular_workshop_construction.json
backport dda 74389 - Add brick construction to camp expansions
=> backport dda 74389 - Add brick construction to camp expansions

src/basecamp.h, src/faction_camp.cpp
Backport DDA 74344 - Make farm plots re-tillable in farming extension version 2
=> Backport DDA 74344 - Make farm plots re-tillable in farming extension version 2

src/item.cpp, src/item_contents.cpp
Backport DDA 74268 - Fix extension cords falling off when items are turned on
=> Backport DDA 74268 - Fix extension cords falling off when items are turned on

src/vehicle.cpp
Backport DDA 74615 - break fake parts when main part breaks
=> break fake parts when main part breaks (#74615)

data/json/overmap/map_extras.json
Backport DDA 74603 - Add CLASSIC to map extras + remove more autonote
While backporting, I noticed some stuff was still autonoted.
=> Backport DDA 74603 - Add CLASSIC to map extras + remove more autonote

src/bionics.cpp, src/bionics.h, src/effect_on_condition.cpp, src/effect_on_condition.h, src/item_factory.cpp, src/martialarts.cpp, src/martialarts.h, src/mod_tracker.h, src/mutation.h, src/mutation_data.cpp
Backport 74565 - Use std::string_view in mod_tracker
=> Backport 74565 - Use std::string_view in mod_tracker

src/mutation.h, src/mutation_data.cpp, src/newcharacter.cpp, src/player_display.cpp
Backport DDA 74525 - Start menu: Selector for trait variants
Backport this, but let people back out of the submenus with the escape key.
Compiles, runs, changes work as intended.
=> Backport DDA 74525 - Start menu: Selector for trait variants

data/json/overmap/overmap_special/specials.json, data/json/overmap/overmap_terrain/overmap_terrain.json
Backport dda 74652 - Give gun show tent a roof
=> Backport dda 74652 - Give gun show tent a roof

build-data/web/index.html, data/json/items/armor/coats.json, data/json/items/melee/bludgeons.json, data/json/monsters/fungus_zombie.json, data/json/monsters/zed-animal.json, doxygen_doc/doxygen_conf.txt, lang/string_extractor/parsers/talk_topic.py, object_creator/creator_main.cpp, snapcraft.yaml, src/generic_factory.h, src/item_factory.cpp, src/main.cpp, src/mapdata.cpp, src/missiondef.cpp, src/monstergenerator.cpp, src/mutation_data.cpp, src/overmap.cpp, src/recipe.cpp, src/rotatable_symbols.cpp, src/translation_manager_impl.cpp, tools/auto_doc_mutations.py, tools/clang-tidy-plugin/CataTidyModule.cpp
Fix translations and clean up lingering "dda"s in code
Translations weren't working because of a misnamed pointer in a file. I found a few others.
- dda -> tlg
- Fix some minor json errors that weren't throwing messages before due to the bad pointers.
=> Fix translations and clean up lingering "dda"s in code

data/json/mapgen/ws_regional_dump.json, data/json/npcs/isherwood_farm/NPC_Barry_Isherwood.json, data/json/overmap/overmap_special/specials.json, data/json/overmap/overmap_terrain/overmap_terrain_waste_junk.json
Backport DDA 74651 - Provide roof for regional dump shack
=> Backport DDA 74651 - Provide roof for regional dump shack

data/json/items/ammo.json, data/json/items/containers/containers.json
Backport DDA 74614 - add tiny bottles and modify nicotine liquid bottles
Smaller, less useful containers!
=> Backport DDA 74614 - add tiny bottles and modify nicotine liquid bottles

data/json/itemgroups/Weapons_Mods_Ammo/guns.json, data/json/itemgroups/Weapons_Mods_Ammo/magazines.json, data/json/itemgroups/Weapons_Mods_Ammo/nested_guns.json, data/json/items/gun/shot.json, data/json/items/magazine/shot.json, data/mods/Generic_Guns/firearms/gg_firearms_migration.json, data/mods/Generic_Guns/magazines/gg_magazines_migration.json
Backport DDA 74613 - Add Mossberg 590M
=> Backport DDA 74613 - Add Mossberg 590M

CMakeLists.txt
Noticed a bunch of builds failing with `clang++-17: error: argument unused during compilation: '-T LGTA_DIR_PREFIX' [-Werror,-Wunused-command-line-argument]`.
Looks like it got caught up in the DDA -> TLG renaming, but Cmake interprets the first two chars as the actual flag (this would result in `-T GTA_DIR_PREFIX`, which isn't referenced anywhere, but `DATA_DIR_PREFIX` is). 
Hopefully fix the clang-tidy builds. Haven't tested but I'm hoping. 
Change the string back to `-DDATA_DIR_PREFIX` from `-TLGTA_DIR_PREFIX`
- rewriting the entire thing in a less janky build system
- installing several clang/cmake setups to build locally
- removing the workflows entirely
Relying on CI to test, fingers crossed it'll be greener.
=> Fix cmake "unused argument" errors in CI

src/activity_actor_definitions.h, src/visitable.cpp
Backport DDA 75020 - Fix deconstruction save/load item_location loss and screwed progress
It was possible when save/loads happened during deconstruction for progress to either be lost or (when NPCs were doing it) for the progress to shoot waaaay into the negative. This should fix both cases.
=> Backport DDA 75020 - Fix deconstruction save/load item_location loss and screwed progress

data/json/effects_on_condition/npc_eocs/appearance_eocs.json
Backport DDA 74665 - Tone down hair growth times
=> Backport DDA 74665 - Tone down hair growth times

data/json/npcs/tacoma_ranch/NPC_ranch_foreman.json, data/json/npcs/tacoma_ranch/NPC_ranch_nurse.json, data/json/npcs/tacoma_ranch/mission_mapgen_tacoma_commune.json
Backport 74674 - Added Tacoma roofs
=> Backport 74674 - Added Tacoma roofs

data/json/items/comestibles/med.json
Backport DDA 74661 - Fixes Description for Xanax
=> Backport DDA 74661 - Fixes Description for Xanax

data/json/npcs/tacoma_ranch/NPC_ranch_doctor.json
Fix tacoma doctor crutch quest
An update to item IDs broke the tacoma doctor quest. 
Switch the item ID, add a response for mismatched crutches, update the advice response.
=> Fix tacoma doctor crutch quest

data/json/mutations/mutations.json
Backport DDA 74117 - Restricted Genetics and possibly other Alpha traits
People were using Alpha as a way to get all stats boosted easily with no drawbacks. Alpha is thematically about being pure, human+, etc., so this just makes sense.
Really this could be a two stage, one that makes non-alpha muts cost way more or something and one that totally blocks them, but it's fine for now.
Restricted Genetics - Alpha trait that prevents you from getting traits from other lines.
=> Backport DDA 74117 - Restricted Genetics and possibly other Alpha traits

src/monster.cpp
Backport DDA 74805 - Cause offspring to inherit parent's friendly value
=> Backport DDA 74805 - Cause offspring to inherit parent's friendly value

src/magic.cpp
Backport DDA 74810 - Fix concentration metamagic sign flipping
=> Backport DDA 74810 - Fix concentration metamagic sign flipping

data/json/npcs/common_chat/TALK_COMMON_ALLY.json, doc/NPCs.md, lang/string_extractor/parsers/talk_topic.py, src/condition.cpp, src/do_turn.cpp, src/game.h, src/game_constants.h, src/npctalk_funcs.cpp, src/overmap_ui.cpp, src/overmap_ui.h, src/sdltiles.cpp
Backport DDA 74093 - Display ordered NPC path on map, move TALK_GOTO_LOCATION to top-level
=> Backport DDA 74093 - Display ordered NPC path on map, move TALK_GOTO_LOCATION to top-level

src/sdltiles.cpp
=> Backport DDA 74841 - fix android bug

src/sdltiles.cpp
Backport 74869 - Typify for android build
Doesn't get the android build fixed, just makes it so something else I backported won't break it.
=> Backport 74869 - Typify for android build

doc/EFFECT_ON_CONDITION.md, lang/string_extractor/parsers/effect.py, src/npctalk.cpp, src/string_input_popup.cpp, src/string_input_popup.h
Backport DDA 75675 - Support string user input in EOC (similar to num_input in `math`)
Mod support in the short term, I'm sure I'll find some use for it though!
=> Backport DDA 75675 - Support string user input in EOC (similar to num_input in `math`)

src/mapgen.cpp, src/visitable.cpp
Backport DDA 75103 & 75188 for performance
It looks like #582 which was intended to fix some bugs/lag/etc introduced a new lag issue. 75103 and/or 75188 ought to clean that all up.
=> Backport DDA 75103 & 75270 for performance

src/mapbuffer.cpp, src/mapbuffer.h, src/mapgen.cpp, src/visitable.cpp
Backport DDA 75103, 75188, & 75270 for performance/crash fixes
#582 introduced a bug from DDA which these should fix.
Compiles and runs.
=> Backport DDA 75103, 75188, & 75270 for performance/crash fixes

data/json/mapgen/robofaq_locs/robofac_mission_chunks.json, data/json/npcs/robofac/NPC_Cranberry_Foster.json, data/json/npcs/robofac/robofac_intercom/robofac_intercom_trades.json
Fix Cranberry's mission and Hub 01 map sale
When I removed leech blossoms, I updated the map chunk they generate in robofac_locs to use a different set of enemies, however I missed that Cranberry's mission was still using a leech blossom as the kill target, so the mission was uncompletable.
There was an additional bug where Hub 01 was paying you a coin for their map, rather than the other way around.
You are now meant to kill the zombie necromancer that spawns at the site, not a nonexistent leech blossom.
- Did the quest, killed the necromancer, which completed it.
NPC following is bugged as hell. I smashed a corpse that Cranberry was smashing, which caused their AI to get stuck and decide to just stand there forever doing nothing. The quest was still completed, but Cranberry is supposed …
=> Fix Cranberry's mission and Hub 01 map sale

src/cata_tiles.cpp, src/cata_tiles.h, src/sdltiles.cpp
Backport 74966 - draw fallback tiles for overmap weather tiles on om
=> Backport 74966 - draw fallback tiles for overmap weather tiles on om

data/json/monsters/zed_fusion.json, src/character.cpp, src/character_body.cpp, src/game.cpp
Improve temperature warnings and reduce spam
Simply put, temperature is a mess. Top to bottom the entire system is built on ancient hard code, characters lack actual body temperatures, stuff overlaps in weird ways that don't really work, and it's laggy as hell.
The most immediate and easy thing to fix is the message spam. So let's do that. Nobody needs to be told that their left foot is warm 50 times a minute.
- Create a struct to house cooldowns for the different messages which can be set per-BP. Since this is only happening to the player character, it won't get out of hand.
- Have the temperature change, windchill, and frostnip messages respect these cooldowns.
- Adjust the messages to be a bit more generalized.
- Adjust the ordering of the messages to ensure that the most dangerous are …
=> Improve temperature warnings and reduce spam

src/anatomy.cpp, src/anatomy.h, src/creature.cpp, src/creature.h, src/mattack_actors.cpp, src/melee.cpp
Melee attacks cannot target 0 hp parts
NPCs in Cataclysm are unfairly durable: For performance/old code reasons, they don't experience a lot of the same debuffs as the player. This is compounded by the fact that like the player, they have (by default) five main bodyparts with five HP pools, and only two of those body parts will cause them to die if their HP reaches zero. This means that you can attack an NPC and do enough times to kill them many times over, only to get shot and killed because it turns out that in 10 attacks, you did 300 damage to their left leg, which only had 80 HP to begin with.
- Melee attacks that target characters (both the player and NPCs) will now bypass body parts which have zero HP. This dramatically curtails the super-durability of NPCs by ensuring that every …
=> Melee attacks cannot target 0 hp parts

data/json/mutations/mutations.json
Minor JSON Linting
Linting just means cleaning up the formatting of JSON files.
=> Minor JSON Linting

data/json/mutations/mutations.json
HUGE and HUGE_OK are post-thresh only
It was possible to get Freakishly Huge, bumping you up to the largest size category, without crossing the threshold. That is not what we want! The lesser versions of the Large and Small size mutations (Little and Inconveniently Large) are OK since they're not that far outside of the normal human range. The good versions (Small and Large) are post-thresh, and Tiny and Huge should never be accessible to pre-thresh humans unless they're wearing power armor or got hit with a shrink ray or something.
- Add threshreq to HUGE
=> HUGE and HUGE_OK are post-thresh only

data/json/mutations/mutations.json
Revert DDA 55005 and fix RDA & vitamin rates
Carnivores and hemovores were experiencing weird RDA readouts and other unintended behavior. Looking into this, I discovered that https://github.com/CleverRaven/Cataclysm-DDA/pull/55005 had made some changes to how vitamin_rates from mutations worked, using reciprocal addition to try to model multiple simultaneous sources of absorption. This made everything way more confusing than it was supposed to be, and was only capable of speeding the decay time up, not slowing it down, as the function only dealt with positives.
- Revert DDA 55005. vitamin_tates are now simple addition or subtraction in seconds to the vitamin's base rate of loss or gain. We are not adding fractions, we are just adding to or subtracting from the denominator of one fraction. …
=> Revert 55005 and fix RDA & vitamin rates

src/consumption.cpp
Actually revert 55005 for real this time
I was tired and distracted and github desktop is stupid so I accidentally reverted part of #640 
un-revert, applying the code fix I wanted. See 640 for details.
=> Revert accidental reversion of reversion (im tired)

data/json/items/generic/dining_kitchen.json
Changes Tupperware containers to slow spoilage of food inside
Make tupperware containers inline with zipperbags.
Changed tupperware containers to have 80% of standard spoilage rate.
Game loads, tupperware containers in game show they spoil at 80% original rate
=> Change tupperware containers to reduce spoilage inline with zipper bags.

data/json/enchantments.json, data/json/itemgroups/Clothing_Gear/clothing.json, data/json/itemgroups/Clothing_Gear/gear.json, data/json/itemgroups/Clothing_Gear/gear_civilian.json, data/json/itemgroups/military.json, data/json/items/armor/eyewear.json, data/json/items/armor/head_attachments.json, data/json/items/armor/integrated.json, data/json/items/armor/misc.json, data/json/monsterdrops/mutant_experimental.json, data/json/monsterdrops/zombie_default.json, data/json/mutations/mutations.json, src/character.cpp, src/creature.cpp, src/handle_action.cpp, src/map.cpp, src/map_field.cpp
Fix IR vision, improve fields, adjust itemgroups
- IR vision was broken
- A bunch of fields were using outdated checks in map_field()
- I wanted to make some game balance adjustments
- Fixed some issues with IR vision. As far as I can tell, it now works as intended.
- Added a simple range limitation to IR. Previously it used your unimpaired_range(), which was generally 60 tiles. This was kind of nutty. While some sources of IR can see quite far IRL, others, such as vampire bat or pit viper senses, are mostly for close range. A temporary compromise has been struck: The range is now one plus (60 * perception / 20), with 60 being the hard cap as it is with normal vision. I intend to revisit this later and have different sources of IR (heat smision, bad IR goggles, good IR goggles) giving …
=> Fix IR vision, improve fields, adjust itemgroups

data/json/ammo_effects.json, data/json/monsters/insect_spider.json, data/json/mutations/mutation_ordering.json, data/json/professions.json
Tileset layering fixes
Some mutations and bionics have been improperly layered for a very long time, even back in DDA.
Move some things around in mutation_layering.json
=> Tileset layering fixes

data/json/items/armor/integrated.json, data/json/mutations/mutation_ordering.json
Adjust integrated armor values
Some integrated armor values were very out of whack. Phelloderm and epicuticle were still far too good, and the bark, scale, chitin, and most of the fur mutations were really out of control.
Sharply reduce the thickness of all of these mutations and increase their encumbrance. Bring the fur mutations up to modern layering standards. Tweak them a bit so that they're more interesting and diverse.
GRAY FUR - Lupine fur is now NORMAL on the torso and SKINTIGHT everywhere else. It's moderately protective.
SLEEK FUR - Feline fur is weaker but only skintight, and has even coverage.
SHAGGY FUR - NORMAL and SKINTIGHT on all BPs, but has the best protection and is water-friendly.
FUR - Much worse protection and coverage for basic fur. It's still decent though! …
=> Adjust integrated armor values

src/item.cpp
Backport DDA 75220 - Add stack calculation
Stackable items, like gasoline, weren't calculated correctly when burning, leading to puddles of gas burning for hours.
Backport 75220, which causes the full stack to burn at once.
Poured a jerrycan of gas on the ground, lit it on fire, watched it burn up very quickly.
=> Backport DDA 75220 - Add stack calculation

data/json/mapgen/farm_supply.json
Nerf farm supply store
The farm supply store was hugely overloaded with basically everything a survivor could want. Being outside of town, it was limited to having only the monsters that spawned inside of it, which posed little threat to even a modestly prepared character.
- Severely reduce the spawns for all loot, going a bit easier on the actual farming tools and supplies - as a rule, a player should usually expect to be able to find at least some of the main sorts of things that a store supposedly sold, even if it's been picked over or looted.
- Add mad militia to both the regular and looted variants of the store. This location is remote, so these enemies aren't likely to break containment and wander around town sniping the player or anything.
- Add a bunch of evil crows to the roof.
- …
=> Nerf farm supply store

src/character.cpp, src/map_field.cpp, src/melee.cpp
Nerf learning from reach attacks
- Players simply cannot help themselves from abusing reach attacks. This is a problem when they're often able to make these attacks against enemies who cannot reach them back.
- The melee skill represents up-close fighting, parrying, etc. and should not be learned from reach attacks anyway.
- Reach attacks no longer teach melee.
- 1/2 the rate of learning from reach attacks in general. This will make it so that they don't teach bash/cut/stab "better" than melee attacks by virtue of not simultaneously teaching melee, and also make reach cheese a worse strategy in general.
- Remove all teaching from reach attacks: Doesn't super make sense.
- Remove teaching from reach attacks where the enemy can't hit back: Too many corner cases to code for.
- Remove …
=> Nerf learning from reach attacks

src/activity_handlers.cpp, src/handle_action.cpp
Fix corpse bleeding and dissection
Pulped corpses were spraying blood everywhere even if they'd already been bleed. It was also possible to dissect pulped corpses despite them being mangled beyond recognition.
- Pulping a corpse which has been bled no longer sprays blood all over. This means if you can safely bleed an acid zombie into a bathtub or something, you can smash them and not have to worry.
- It is no longer possible to dissect pulped corpses.
- Bloodfeeders should be able to drink from corpses, but the way handle_liquids is set up makes this impossible until I can throw a hook in there for it. That isn't a huge priority right now, so bats will still need to carry bottles around.
- Streets should have storm drains that have LIQUIDCONT but just delete all their contents.
- …
=> Fix corpse bleeding and dissection

src/game.cpp
Climbing is an explosive activity
Climbing was an extreme activity. It's something that is extremely strenuous IRL, and in-game only takes a couple of seconds to do, which means that like melee it qualifies as an explosive activity. This includes climbing up and down trees, drainpipes, ledges, ropes, and (for mutants) scaling walls. This makes this kind of movement a liiiittle less OP, but shouldn't really throw the brakes on anybody's gameplay.
EXTRA->EXPLOSIVE
=> Climbing is an explosive activity

src/activity_handlers.cpp
Further butchery improvements
On further inspection, butchery was doing a lot of very stupid things.
- All butchery now spills blood everywhere unless the corpse has been bled.
- Since blood is spilled everywhere as a field, it is no longer dropped as an item when doing butchery actions other than bleeding.
- Greatly reduced the gibs that go all over when you field dress stuff.
- Corpse damage is handled through several flags as well as actual damage to the corpse item, but the flags were not being appropriately used in all cases. Added checks for gibbed and pulped corpses, reducing yields or making recovery impossible for these corpses.
- Made gibbing/pulping/malnutrition reduce butchery yields further.
- Bleeding a corpse with no containers present pours the blood onto the ground in a …
=> Further butchery improvements

data/json/mutations/mutations.json
Adjust bad back and light/hollow bones
Sylvan, Slime, and Avian were getting shafted bad by the carry weight reduction on hollow bones, which was a whopping 40%. Birds and slimes in particular were also getting hit by bad back, which was making even reasonably strong characters unable to really carry anything. This got into "unplayably bad" territory. It can be offset with titanium skeletal bracing, but that shouldn't be a requirement to play these mutations at all!
- Bad Back was a 30% reduction, it is now 20%..
- Light Bones was a 20% reduction, it is now 10%.
- Hollow Bones was a 40% reduction(!), it is now 25%.
- Light and Hollow Bones have had their speed bonuses nerfed to 10% and 15% respectively.
- Hollow Bones now confers a 10% stamina regen buff. This is something birds are …
=> Adjust bad back and light/hollow bones

.github/workflows/matrix.yml
Bumped llvm from version 10 to 13, mostly took some changes from DDA, [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/80524)
Recently upgraded to Kubuntu 25.04 and immediatly got a segfault when running `cataclysm-tlg-tiles`. Then I checked if dda had the same issue and it doesn't. 
Thus I looked at tlg with `gdb` and got this:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff79709b8 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<true>(char const*, unsigned long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
```
So I suspect fuckery with different versions of `libstdc++6`
Newer versions of llvm/clang link against newer versions of libstdc++6, so I hope the segfault will go away.
:disappointed: 
I'm not …
=> Fixing Linux builds

src/activity_handlers.cpp, src/game.cpp, src/item.cpp
Frozen zombies can't revive, actually prevent dissecting pulped corpses
I tried to make it impossible to dissect pulped or otherwise catastrophically damaged corpses, but I only disabled the activity, not selecting it from the menu. This led to some issues! Also I thought it would be funny if frozen corpses would not revive.
- Prevent frozen corpses from reviving
- Create an "intact" condition and have it negated by skinning, field dressing, quartering, gibbing, or pulping the corpse. Bleeding is OK.
HE HAS NO ORGANS
HE HAS NO SKIN
THIS KONG
IS A SKELETON
It's possible that if you leave a corpse in deep freeze for more than a day it will wake up the split second it thaws because its timer keeps running. This is funny and inconsequential enough that I don't care about it.
=> More fun with corpses

data/json/butchery_requirements.json, src/activity_handlers.cpp, src/game.cpp, src/monattack.cpp
Try not to go insane while fixing corpses yet again
There was an existing DDA bug which was causing corpses to skip getting the PULPED flag applied to them during smashing sometimes. This threw my changes in the last few PRs into disarray, but we're all good now.
- Properly apply the PULPED flag
- Add secondary checks for corpse damage, just in case
- Make human-sized corpses require a proper setup for full butchery (but not for bleeding)
- Dramatically reduce the meat yield from pulped corpses
- Slightly increase the damage done by monattack::eat_carrion() and verify that it's properly applying flags
- Smash corpses, attempt to butcher them
=> Try not to go insane while fixing corpses yet again

data/json/furniture_and_terrain/furniture-decorative.json, data/json/mapgen/robofachq_static.json
Backport DDA 76111 - Add indoor flagpole and use it for Hub01 American flags
=> Backport DDA 76111 - Add indoor flagpole and use it for Hub01 American flags

src/cata_tiles.cpp, src/cata_tiles.h
Backport DDA 74801 - tile layering supports variants
Make Ultica stop complaining
=> Backport DDA 74801 - tile layering supports variants

doc/TILESET.md, src/cata_tiles.cpp, src/cata_tiles.h
Backport 78199 - Less Verbose Tileset Layering
Ultica no longer gives error messages
I cannot tell you what a pain in the ass it was to get this very simple PR backported thanks to its many, many prereqs.
=> Backport 78199 - Less Verbose Tileset Layering

src/mattack_actors.cpp
The code for handling monster dragging sets up an intersection of two sets of tiles:
1. The square of neighboring tiles of the dragger
2. A square with variable radius around the tile which is on the opposite side of the dragger from the draggee
Both of these squares are clamped to the reality bubble by map::points_in_radius (more or less), which means that if the second set was just one tile that ended up outside the reality bubble, the intersection set would be empty.
The original code was assuming that this set would never be empty, trying to pick a random element from the intersection set unconditionally, but in this case, this was causing a segmentation fault crash.
Return from melee_actor::do_grab if the intersection set is empty.
Allow the dragging mob to go out of the reality …
=> fix segfault when mobs drag mobs at edge of reality bubble

data/json/professions.json
Fix Vagabond equipment
The vagabond profession had some weird conflicts with its starting equipment.
- Remove the gendered underwear, backpack, and wool socks.
Loaded it up. Looks good.
=> Fix Vagabond equipment

data/json/furniture_and_terrain/replace_concealment.sh, src/activity_handlers.cpp, src/cata_tiles.cpp, src/game.cpp
Block overmap sight through solid terrain
Characters with sufficient overmap sight ability (IE Scout, high per) were sometimes able to see through solid earth/rock
Terminate the overmap sight line the moment the viewer encounters a 5 view cost tile, no matter what.
This may need revisiting if the player ever gains a way to see through solid walls, but I assume that e.g. clairvoyance or quadcopters would use a different function, so it probably doesn't matter.
Spawned a character with Scout, gave him a telescope. Peeked into basements, walked into basements, could not see through solid earth on the map.
=> Block overmap sight through solid terrain

src/activity_handlers.cpp
Fix butchery segfault
Butchery was deleting the corpse in some cases before it could finish placing all the meat and blood on the ground, which seems to be the cause of some recently reported segfaults following #666 etc.
Use a bool to indicate whether the corpse should be deleted, and delete it at the end of the process instead of doing it right away.
Spawned in and butchered some stuff. No issues, but it was a slippery bug so I'm not 100% sure it's fixed.
The weird part is that I didn't change the code there, it was doing this for years in DDA with no issue. So why was it segfaulting now? Well, (confused Tim Allen grunting)
Special thanks to @doublescale and @Maepple for finding the potential issue and cooking this fix up.
=> Fix butchery segfault

data/json/items/armor/legs_armor.json, data/json/items/armor/suits_protection.json, data/json/items/tool_armor.json, data/json/npcs/talk_tags_chat.json, data/json/obsoletion_and_migration/migration_items.json, data/json/recipes/armor/pets_cow.json, data/json/recipes/armor/pets_horse.json, data/json/recipes/armor/suit.json
Update samurai armor, survivor masks, and various dialog
- The o-yoroi was super outdated
- The plated leather armor was too strong and sort of redundant with brigandine+o-yoroi
- Some gas masks didn't have proper layers, materials and thicknesses
- A lot of greaves and pants didn't allow tails
- A couple bits of dialog were outdated
- Delete plated leather armor and migrate it to o-yoroi
- Update and modernize o-yoroi
- Update cow and horse plated leather barding to use a different copy-from
- Add xl and xs o-yoroi
- All gas masks should be compatible with NVG helmet attachments
- Allow most greaves, riot armor, plate and chain mail (but not faraday), and some other odds and ends to be work with tails
- Rewrite a couple bits of random dialog to remove outdated references to blob healing …
=> Update samurai armor, survivor masks, and various dialog

data/json/furniture_and_terrain/furniture-decorative.json, data/json/items/generic/toys_and_sports.json, data/json/materials.json
Fix mannequin deconstruct bug
Deconstructing a mannequin via * was causing a segfault because it had no deconstruction values defined. I also noticed that mannequins were made of wood. IRL mannequins are generally fiberglass.
- Add a deconstruct object in the json
- Swap the material over to fiberglass
- Change the bash result to epoxy chunks (we don't have fiberglass chunks yet, and I don't think we need them)
- Reduce the bash damage and weight on the mannequin item
- Spawned a mannequin, placed, examined, placed, deconstructed, made a decoy mannequin, killed it, got a damaged mannequin item. All good!
=> Fix mannequin deconstruct bug

data/json/furniture_and_terrain/furniture-decorative.json
Mannequins aren't plastic
Accidentally left the bash results as epoxy chunks.
Bashed mannequins drop epoxy chunks, not plastic. They're made of fiberglass.
=> Mannequins aren't plastic

data/json/recipes/armor/legs.json, data/json/recipes/armor/torso.json
Changes to be committed:
modified:   data/json/recipes/armor/legs.json
modified:   data/json/recipes/armor/torso.json
Made Survivor Cargo Pants and Survivor Longcoat properly use the rubber sealant spray tool.
Crafting survivor gear has been changed to use rubber sealant spray as a tool instead of using rubber sealant as a component. Survivor cargo pants and longcoat were missed in that update.
Change requirement of rubber sealant to requirement of charges of rubber sealant spray.
Console spawn in the clothes.
Started the game, made a pair of pants, seems to work.
=> RubberSealant

data/json/items/armor/arms_armor.json, data/json/items/armor/boots.json, data/json/items/armor/gloves.json, data/json/items/armor/helmets.json, data/json/items/armor/legs_armor.json, data/json/items/armor/suits_protection.json, data/json/items/armor/torso_armor.json, data/json/materials.json, data/json/obsoletion_and_migration/migration_items.json, data/json/recipes/armor/legs.json, data/json/recipes/armor/torso.json
Update armor protection and encumbrance
I have made a lot of sweeping armor changes which made the mechanics and coverage work more like I wanted, but several items still had improper protection values. This is one of those things that you never really finish tweaking, but now's as good a time as any to fix up a bunch of the more common sets and pieces.
Ignore the acid and fire values here - this menu is currently incorrectly calculating some armor values. It's about right for the encumbrance, bash/cut/stab/bullet, and coverage averages though. The main thing is that plate mail is now as good as it's meant to be, instead of worse than leather.
I didn't change the plate carriers or longcoat, but everything else here got a review. I also haven't changed riot armor, which I know is popular …
=> Update armor protection and encumbrance

src/iuse_actor.cpp
Backport DDA 75397 - Made use action appliance deployment work properly
Necessary prerequisite for DDA 77092, which will eventually fix the solar suitcase duplication bug.
=> Backport DDA 75397 - Made use action appliance deployment work properly

src/activity_actor.cpp, src/activity_handlers.cpp
Reduce fun and max fun from reading
Books used to have such a short morale boost that it wasn't really worth reading them. I made it last longer in #695 but this made us discover that book morale is for some reason capped at fun * 15. A book lover could potentially get 90 morale by reading a book 3 times! What the heck! Nobody ever noticed I guess because it wasn't ever worth doing.
- Book base and max fun were fun * 5 and fun * 15. They are now fun and fun * 10. If you want to try and read a playboy 10 times as a book lover to get 60 morale for the 20 remaining minutes your buff lasts, then that is between you and the Lord.
readan books
=> Reduce fun and max fun from reading

data/title/en.alt1, data/title/en.christmas, data/title/ru.alt1
Add alt and christmas title screens
Users BananaBonanza and Meadevil contributed a Christmas and an alternative ASCII title screen in #49 
- Add BananaBonanza's Christmas title screen.
- Add Meadevil's ASCII art as an alt screen.
- Adjust the above slightly and add it as an alt screen for Russian
The Christmas one will pop up around the IRL holiday, the new alt screen will pop up randomly sometimes when you open the game if you're playing in English or Russian.
Loaded the game and saw the cool new art!
=> Add alt and christmas title screens

data/json/itemgroups/Drugs_Tobacco_Alcohol/drugs.json, data/json/itemgroups/Drugs_Tobacco_Alcohol/tobacco.json, data/json/itemgroups/SUS/domestic.json, data/json/itemgroups/collections_domestic.json, data/json/itemgroups/food_service.json
Fix auto-generated itemgroup spam
The charge removal from solid comestibles a few years back left a lot of things in quite a state. Players noticed that several items were still spawning in comically huge piles thanks to bugs remaining in the automatically generated itemgroups that were done around that time.
- Fix tea leaf spam
- Fix powdered milk spam
- Fix electronic cigarette spam
- Fix cough syrup spam
Electronic cigarettes don't appear to work properly, you just smoke the whole thing in one second and then it's gone. I assume these are just disposable ecigs - they ought to work like the advanced kind but have an internal battery and reservoir you can't take out (which can be salvaged if you deconstruct em!)
Spawned in, things seem OK so far.
=> Fix auto-generated itemgroup spam

data/json/monstergroups/misc.json, data/json/monstergroups/wilderness.json, data/json/monsters/insect_spider.json, data/json/monsters/reptile_amphibian.json
Introduce life cycles for dragonflies and spiders
Bugs were evolving on a fixed timer, breeding, and never dying. This meant that areas would eventually fill up with an improbable number of cow-sized whatevers. This harmed both enemy variety and gameplay as it turned certain areas into slogs.
- Trapdoor spiders, web spiders, wolf spiders, cellar spiders, and giant dragonflies have been moved back to a half-life system for most of their evolutions. This means that you may see some of their larger forms early, but generally you should be seeing a mix of different enemy types.
- Fused dragonflies and the mega forms of the spiders listed now die off after some time, usually with a half-life of around 3 weeks. These animals all lay eggs, so they should be able to maintain their populations …
=> Introduce life cycles for dragonflies and spiders

data/json/items/armor/arms_armor.json
Pauldrons aren't sided
Leather and plate mail pauldrons had the "sided" object set to true, meaning despite being a pair they'd only go on one shoulder.
Delete that line. Now they're a pair.
=> Pauldrons aren't sided

data/json/monsters/mammal.json
Makes lambs, goat kids, and llama calves tamable like cow calves are.
Cow calves are tamable with cattle food, but lambs, goat kids and llama calves are not.  This makes all of them tamable.
Makes lambs, goat kids and llama calves tamable.
Added the line:
"petfood": { "food": [ "CATTLEFOOD" ], "feed": "The %s seems to like you!  It lets you pat its head and seems friendly." },
to each of the above, copied from cow calves.
Make cow calves untamable to be consistent.
Spawn cattle food and a lamb, goat kid and llama calf.  Confirm that each can now be tamed with cattle food.
=> Make lambs, goat kids and llama calves tamable like cow calves

data/json/monsters/zed-winged.json
Fix winged zombies and unstable flesh-raptors
Unstable flesh-raptors weren't working, zaptors weren't burning out, flesh-raptors had damage and arpen designed for DDA armor values, and winged zombies were pretty unimpressive.
Restore the self-destruct attack to unstable flesh-raptors, give winged zombies some dodge. reduce damage and arpen on flesh-raptor attacks, zaptors burn out into unstable flesh-raptors after a couple of days, similar to how shockers burn out.
=> Fix winged zombies and unstable flesh-raptors

data/json/items/relics/altered_items.json
Fix artifact varsity jacket copy-from
The artifact varsity jacket was using the stats and materials of a leather jacket.
Now it's a varsity jacket
=> Fix artifact varsity jacket copy-from

data/json/npcs/robofac/robofac_ancilla_npcs/NPC_ANCILLA_DOCTOR.json
Stop Hub 01 doc from trading HGC for 1% of their value
The Hub 01 doctor was selling HGC for 50 cents. They're supposed to be fifty dollars!
- 50->5000
- Reduce some of his vendor stock.
=> Stop Hub 01 doc from trading HGC for 1% of their value

data/json/furniture_and_terrain/terrain-walls.json, data/json/recipes/food/brewing.json, data/json/recipes/food/dry.json, data/json/recipes/food/milling.json, src/map.cpp
Fix ballistic glass
Due to some backports, map::shoot() got broken again! The stats for balllistic and reinforced glass also needed some fixing.
- Highly accurate shots cannot pass through solid objects. Third time should be the charm (until another backport ruins it!)
- Improved laser_passthrough logic
- Adjust bash yields for ballsitic and reinforced glass
- Adjust bash strength for ballistic and reinforced glass
- Adjust damage reduction for ballistic and reinforced glass
- Make damage < 1 destroy the projectile
Spawned in with a turret and some ballistic glass. Most of its bullets were stopped by the blast, some hit me for single digit or damage in the teens.
=> Fix ballistic glass

data/json/recipes/food/vegetable_dishes.json, data/json/recipes/recipe_food.json, src/map.cpp
Prevent 0 damage hits from trying to apply damage
Ranged hits reduced to fractional amounts of damage by hitting cover get rounded to 0, but were still being passed to the hit function. This was occasionally damaging the player's equipment, which is not appropriate.
If damage is reduced to less than 1, cancel the attack.
=> Prevent 0 damage hits from trying to apply damage

data/json/mapgen/farm_stills.json, data/json/mapgen_palettes/orchard_apple.json
Reduce apple orchard and grape farm food spawns
- Grape farms and apple orchards had preposterous amounts of pickable fruit available despite ripening six months into a full blown apocalypse.
- Grape farms had wild grape bushes and not cultivated ones, meaning they never overgrew and would come back year after year.
- Some corn farms still had way too much food.
- Change grape farms to use crop furniture instead of wild grape bush terrain.
- Dramatically reduce the pickable fruit terrain/furniture.
- Add farm pests to the grape farm
Spawned in and visited both locations. Seems good.
=> Reduce apple orchard and grape farm food spawns

data/json/npcs/other/meteorologist.json
Fixed it so the meteorologist will give mission
Update meteorologist.json so meteorologist can give mission
To fix meteorologist mission
Took proposed fix from https://github.com/CleverRaven/Cataclysm-DDA/issues/75960
and changed
"condition": { "math": [ "time_since(n_time_mission_meteorologist_wait)", ">=", "time('2 d')" ] }
to
"condition": { "math": [ "time_since( value_or(n_time_mission_meteorologist_wait, time('cataclysm') ) )", ">=", "time('2 d')" ] }
Spawn meteorologist
Wait 2 days
Confirm that they can give their mission now
=> Update meteorologist.json so meteorologist can give mission

data/raw/keybindings.json, src/game.cpp
Implemented a new action that lets you [V]iew the enemy interrupts an activity of the player.
When an enemy triggers a distraction popup on long time-based activity, the menu doesn't give you enough information of it.
Add a new button whenever a distraction happens [V]iew enemy.
Adding a more custom message similar to "Spotted a zombie 25 tiles to the north-east!" at the distraction popup.
Basic manual testing.
=> Add button to activity cancel

data/json/npcs/refugee_center/surface_staff/NPC_free_merchant_teamster.json
Fix missing teamster dialog
The Refugee Center teamster had a missing response for asking them to help with the cleanup effort.
- Added a response. I didn't feel like tracking down the commit and doing a complicated revert, so for the sake of compliance with our license, I wrote a new one.
- Removed an orphaned bit of dialog relating to Rubik.
Game loads. That means it works, right??
=> Fix missing teamster dialog

src/avatar.cpp, src/game.cpp
Wielding an item releases your grab
It was previously possible to grab an enemy, wield a weapon, and then hit them with it while grabbing them. This was unintentional.
Wielding an item while grabbing will now release your grab.
It is eventually planned that certain characters (IE cephalopods) will be able to wield things while grabbing, and that one-handed items will be wieldable but apply a penalty to your grab_strength.
=> Wielding an item releases your grab

data/json/items/tool_armor.json
Make 5-point anchors wearable for all
5-point anchors are important items, but they weren't wearable by tiny characters. This was due to an oversight in how sizes were implemented. Since the item is simply a device strapped around the wearer's torso, it should be trivial to fit on pretty much anyone.
Remove the OVERSIZE flag and replace with UNRESTRICTED. These items will still indicate that they are too large or too small for tiny/huge characters, but are still quite usable. Tiny characters get 2 extra encumbrance from them, but that's no big deal.
Equipment sizes need to be entirely redone, but (exhausted sigh)
Tried wearing an anchor as a tiny character, a huge character, and a character with a roomy shell (which restricts torso gear but should still allow OVERTOP items like the …
=> Make 5-point anchors wearable for all

data/json/hobbies.json
Remove fleet-footed from hobbies
Some hobbies still offered fleet-footed. That's not intended!
Removing fleet-footed entirely.
Game loads, runs, fleet-footed is no longer available.
=> Remove fleet-footed from hobbies

data/json/items/melee/swords_and_blades.json, data/json/recipes/weapon/cutting.json
Remove survivor machete+Backport DDA 72536 - Remove rapid strike from knives
A few of our knives still had Rapid Strike. I noticed a few other issues during this backport that I wanted to fix too.
- Remove rapid strike from most knives.
- Once again, cavalry sabers are not fencing weapons.
- Reduce the blocking ability of a few shitty swords.
- Remove the survivor machete and its recipe.
Loads and runs, wee
=> Remove survivor machete+Backport DDA 72536 - Remove rapid strike from knives

data/json/itemgroups/Clothing_Gear/clothing.json, data/json/items/armor/gloves.json, data/json/npcs/EOC_talkers/xedra_merc.json, data/json/npcs/Kindred/NPC_Darren_Cooper.json, data/json/npcs/robofac/robofac_ancilla_npcs/NC_ANCILLA_GRUNT.json, data/json/obsoletion_and_migration/migration_items.json, data/json/requirements/melee.json
Fix gloves and finish removing survivor machete
- A bunch of gloves had missing or too little encumbrance. This bumps them up.
- I forgot to remove survivor machetes from a few places.
- Add encumbrance.
- Remove references to the survivor machete.
- Migrate the survivor machete.
=> Fix gloves and finish removing survivor machete

data/json/items/comestibles/carnivore.json, data/json/recipes/recipe_food.json
Backport 74888 - Audit Carnivore for items with volumes indivisible by 50ml
Fix behavior of small meat items, which were in some cases not counting as meat or human flesh.
=> Backport 74888 - Audit Carnivore for items with volumes indivisible by 50ml

data/json/professions.json
Backport 74889 - Burglar has safecracking
=> Backport 74889 - Burglar has safecracking

src/math_parser_diag.cpp
Backport DDA 74893 - Make the time_until function positive when arg is now
Improve timed event tracking
=> Backport DDA 74893 - Make the time_until function positive when arg is now

data/json/effects_on_condition/npc_eocs/godco_npc_eocs.json
Backport DDA 74959 - add missing threshes to NECC blacklist
=> Backport DDA 74959 - add missing threshes to NECC blacklist

data/json/bionics.json, data/json/items/bionics.json
Backport DDA 74947 - Artificial Night Generator do[es] not grant invis
The CBM puts darkness on you, it doesn't need to also make you invisible, and it shouldn't be doing that anyway cause some monsters can see in the dark.
=> Backport DDA 74947 - Artificial Night Generator do[es] not grant invis

src/consumption.cpp
Backport DDA 74977 - fix negative KCAL and VITAMIN_ABSORB_MOD enchantments
=> Backport DDA 74977 - fix negative KCAL and VITAMIN_ABSORB_MOD enchantments

doc/EFFECT_ON_CONDITION.md, src/condition.cpp, src/npctalk.cpp
Backport DDA 74996 - Better EoC support for field search
=> Backport DDA 74996 - Better EoC support for field search

data/json/mapgen/cabin.json
Changes to be committed:
modified:   data/json/mapgen/cabin.json
Changed the wild rabbits at Lapin's cottage to tameable domestic ones.
Able to get rabbits as a reward for doing missions for Mr. Lapin.
Changed mon_rabbit in mapgen/cabin.json to mon_rabbit_domestic
None
Spawned the cabin. Rabbits are the correct type. Tamed a rabbit using cattle fodder.
=> Domestic rabbits at Lapin's

src/bionics.cpp
74999 - Prevent automatic assignment of invlets to passive bionics
=> 74999 - Prevent automatic assignment of invlets to passive bionics

src/ballistics.cpp
Backport DDA 75002 - Limit shot targets to the reality bubble
=> Backport DDA 75002 - Limit shot targets to the reality bubble

src/vehicle.cpp
Backport DDA 75031 - Blocked negative part index from being used
=> Backport DDA 75031 - Blocked negative part index from being used

src/map.cpp, src/map_field.cpp
Backport 75038 - Improve fire behavior
Stop fire from throwing a bunch of warnings and burning forever
=> Backport 75038 - Improve fire behavior

data/json/flags.json, doc/JSON_FLAGS.md, src/mutation.cpp
Backport DDA 75043 - Add TEMPORARY_SHAPESHIFT flag
Mostly just mod support, but I may make use of this in the future in main.
=> Backport DDA 75043 - Add TEMPORARY_SHAPESHIFT flag

src/faction_camp.cpp
Backport DDA 75047 - Camp storage meal abortion works properly
=> Backport DDA 75047 - Camp storage meal abortion works properly

data/json/furniture_and_terrain/furniture-decorative.json, data/json/furniture_and_terrain/furniture-fireplaces.json
Backport DDA 75052 - Added deconstruction to deployed_items needing it
=> Backport DDA 75052 - Added deconstruction to deployed_items needing it

data/json/weather_type.json
Backport 75076 - Fix weather typo
=> Backport 75076 - Fix weather typo

data/json/flags.json, doc/JSON_FLAGS.md, src/avatar_action.cpp, src/game.cpp
Backport DDA 75092 - Add ITEM_WATERPROOFING flag
Mod support. This is not used in main.
=> Backport DDA 75092 - Add ITEM_WATERPROOFING flag

data/json/mapgen/farm.json, data/json/overmap/overmap_mutable/farm_mutable.json, data/json/overmap/overmap_terrain/overmap_terrain_agricultural.json
Backport DDA 75124 - apiary terrain
Adds apiaries to farms
=> Backport DDA 75124 - apiary terrain

data/json/bionics.json, data/json/itemgroups/Weapons_Mods_Ammo/guns.json, data/json/mutations/mutations.json, data/json/obsoletion_and_migration/obsoletion.json, data/json/scenarios.json, src/game.cpp
Ditch ursine eye mutation, improve mesopia
Mesopia was an EYE/VISION mutation, which made it conflict with night vision. This was done for some complicated reasons that don't matter anymore, so let's fix it.
- Obsolete URSINE_EYE
- Give MESOPIC to URSINE
- Change MESOPIC to have no category, but be canceled by the dummy human eye mutation, as well as telescopic eyes
- Remove URSINE_EYE from mutant scenarios, replace with MESOPIC
- Remove MESOPIC from trog, but it makes too much sense.
=> Ditch ursine eye mutation, improve mesopia

data/json/itemgroups/Locations_MapExtras/locations_commercial.json, data/json/itemgroups/vehicles_fuel_related.json, data/json/mapgen/petstore.json
Nerf pet store and car trunk loot
Pet stores had an obnoxious amount of pet food in them due to auto-generated itemgroups and charge removal. Car trunks had a ridiculously high chance of having a toolbox.
- Drastically cut the chances of a toobox being in a car trunk
- Add a tiny chance for a towel or blanket to be in a car trunk
- Drastically cut the pet food in pet stores
=> Nerf pet store and car trunk loot

data/json/monsters/zed-pupating.json, data/json/monsters/zed_misc.json
Nerf frog mothers, stop pupating zombie cheese
- Decoy pupating zombies now always eventually evolve into real ones. They're not decoys, they're just not finished cooking.
- Decoy pupating zombies have reduced skill to prevent being used for training exploits.
- Reduced the regen on decoy pupating zombies.
- Reduced the regen on frog mothers. They had fucking 40. For reference, a relentless hulk feels almost unkillable with just 15.
A DOES_NOT_TRAIN flag would be nice.
=> Nerf frog mothers, stop pupating zombie cheese

data/json/monsters/zed-pupating.json, src/monmove.cpp
Reduce SLUDGETRAIL and fix pupa
- SLUDGETRAIL was making a perfect 3 tile wide trail of sludge, which looked bad visually.
- The recent pupa changes accidentally redundantly defined 0 dodge, which caused an error message.
- SLUDGETRAIL now checks if RNG 0,3 > 0, resulting in a 1/4 chance that it won't sludge a candidate tile.
- Delete the extraneous line in the pupating zombie jsons
=> Reduce SLUDGETRAIL and fix pupa

data/json/professions.json
Change the starting proficiencies of the baseball player profession to bludgeons instead of maces.
Baseball players had the wrong weapon proficiency at character generation, since bats are bludgeons, not maces.
Made a new character with the baseball player profession. They had the correct proficiencies
=> Update baseball player weapon proficiencies

doc/OVERMAP.md
Fixed minor formatting error in the `OVERMAP.md` doc file.
To maintain a consistent formatting style in the doc files.
=> fixed 'see_cost' values table

data/json/items/melee/unarmed_weapons.json, data/json/items/tool/workshop.json, data/json/mutations/mutation_ordering.json, data/json/recipes/weapon/cutting.json
Fix troglobite mutation layering
One of the trog mutations, Solar Sensitivity, was layering incorrectly because it wasn't included in mutation_ordering.json.
Add it, shuffle some other stuff around.
This probably needs another pass, with fur and stuff on a layer above skin, and accessories like thorns on a layer above that.
=> Fix troglobite mutation layering

data/core/game_balance.json, src/character.cpp, src/debug_menu.cpp, src/kill_tracker.cpp, src/player_display.cpp
Remove dead mod code
Removes some dead code related to mods we don't support, as well as a few references to portal storms.
Compiles and runs. Existing saves may experience error messages the first time they are loaded.
=> Remove dead mod code

src/crafting_gui.cpp, src/map.cpp, src/version.cpp
Fix crash while approaching certain vehicles
Something got lost in the shuffle while doing typification backports, and vehicle memory was crashing the game when the player entered certain areas.
Re-add two deleted lines to an iterator in map.cpp, make sure they're done at the end of it so they don't trip a segfault
Was able to load a map where the crash was occurring and enter the area without issue.
=> Fix crash while approaching certain vehicles

data/json/harvest_dissect.json, data/json/items/comestibles/carnivore.json, data/json/items/comestibles/mutagen.json, data/json/monsters/jabberwock.json, src/mutation_data.cpp
Fix stray threshold_min definition, adjust mutagen
threshold_min was set to 600 in mutation.h in #785 but I didn't catch that it was redefined in mutation_data.cpp, overriding what I'd set.
- Set threshold_min to 600.
- Slightly reduce and randomize the amount of typed mutagen in both infusion and regular mutagen.
- Increase the beast mutagen in jabberwock hearts and make the blood properly divide it into 5 parts (so it's the same if you eat the heart or just get the blood).
- Make jabberwock hearts also attainable via dissection, just because that's what most people would think to do.
- Took some alpha infusion and crossed the threshold.
- Ate a jabberwock heart and saw that I got beast mutagen.
=> Fix stray threshold_min definition, adjust mutagen

src/mapdata.cpp
Crashes started happening to Arch Linux users running on recently updated systems.
This crash was not happening on C:DDA.
All affected users seemed to have the same crash stacktrace, pointing at the initialization of map_bash_info.drop_group in an initialization list in src/mapdata.cpp .
It's possible that a change in the C/C++ runtime libraries caused some static initializations to happen in a wrong order.
Pull the initialization of map_bash_info.drop_group from the initializer list into the body of the constructor.
Wait for November 2024 backports, and tell Linux users not to update their system ever.
Game crashed on startup before, it runs on my Arch Linux machine after the fix.  Can load existing games, save, and start new runs.
While comparing the critical code with C:DDA, I came …
=> Fix Arch Linux segmentation fault on startup

src/avatar.cpp, src/character.cpp, src/character.h, src/handle_action.cpp, src/item.cpp
Unify grapple release function
There was a workaround allowing people to wield items while grappling if they used a sheath. The function also needed to be unified rather than redundantly typed out every time the game needed to make you let go of somebody.
- Create a new function, Character::release_grapple(), which gets called in on_wield(), so you should let go of grapples any time something comes into your hand by any means.
Eventually I want to have some mutations allow you to maintain multiple grabs or wield stuff while grabbing. I think even baseliners should be able to hold a half-strength grapple with a small weapon in hand.
Spawned in, grappled, wielded stuff, used a sheath, all works as intended.
=> Unify grapple release function

data/json/items/melee/misc.json
Tasers were too big for loot pools to spawn them,  they were missing similar flags in json that other pistols use to maintain a consistent size.
Fix loot pools, allows tasers to spawn on zombie cops, and makes them similar to other pistol sizes.
Added` "magazine_well": "250 ml",` to the pocket data
Game runs, checked in game for total stungun/taser size, and shows 0.45l
=> Taser volume size balance

src/item.cpp, src/map_extras.cpp
Fix rot timers
- One of the hardcoded map extras was spawning some corpses. These were 20 days old, which is probably not a big deal but could have been causing a couple of super-evolved zombies to show up.
- Food in houses was sometimes still spawning fresh, even weeks into the game. This shouldn't be the case for anything that isn't sealed!
- Change the date to spawn the corpses in that one map extra, so they spawn on the usual game start date instead.
- Adjust the logic in randomize_rot() to better handle things in pockets.
Ran around in summer, didn't find any fresh food at all.
This is not likely to be the cause of some of you seeing evolved bad guys on day one. That's almost certainly just normal outliers and selection bias.
=> Fix rot timers

data/json/items/armor/suits_protection.json
Loosened hauberk is outer
Chainmail hauberks fit on the NORMAL layer and are meant to become OUTER when loosened. This wasn't working because the flag wasn't actually set on the regular hauberk, and I guess just having NORMAL by default isn't removed when you extend the OUTER flag to a copy-from'd version.
Manually set the flag on the regular hauberk and manually delete it from the loose version.
Spawned a hauberk, loosened it, saw its layers change.
=> Loosened hauberk is outer

data/json/recipes/other/parts_construction.json, data/json/vehicles/carts.json
Add dashboards to golf carts
Golf carts weren't chargeable because they lacked electronics controls or dashboards to plug into.
- Give them dashboards
- Fix a random typo
Add a charging port part that allows power cables to plug in.
Spawned both golf carts, observed dashboards.
=> Add dashboards to golf carts

data/json/furniture_and_terrain/terrain-windows.json
Fix barred window frame
The empty window frame with bars accidentally had 100 coverage, as if it still had glass, but it had bash stats for the metal bars, so it became an impenetrable steel wall basically.
Coverage 100 -> 15
=> Fix barred window frame

data/json/itemgroups/tools.json, data/json/items/ammo_types.json, data/json/items/containers/containers.json, data/json/items/generic.json, data/json/items/tool/misc.json, data/json/obsoletion_and_migration/migration_items.json, data/json/recipes/recipe_traps.json, data/json/recipes/weapon/ranged.json, data/json/requirements/materials.json, data/mods/Sky_Island/upgrade_missions.json, data/mods/innawood/migration_items.json
Simplify superglue and reduce spawn amount
I backported some changes to superglue that came with a little more granularity than I wanted. Superglue amounts also seemed kinda off in the requirements jsons.
- Simplify superglue bottles so there's just one kind.
- Reduce superglue spawns to 1-10 per bottle.
- Reduce superglue requirements so people don't need dozens of units for stuff.
- Obsolete the two unique superglue bottle types.
- Update sky islands and innawood to reflect this change.
- Make superglue spawn in a single bespoke sealed container that can't store anything else.
- Make it charge-based like rubber sealant.
- Spawned glue, looks good
- Used glue to make stuff, looks good
=> Simplify superglue and reduce spawn amount

data/json/effects.json, src/character_escape.cpp, src/melee.cpp, src/monster.cpp, src/trapfunc.cpp
Beartraps drop properly and don't prevent attack
- It was impossible to attack an enemy while downed or stuck in a beartrap or snare, even if you wanted to
- Beartraps were dropping at the point where you set them off, even if you had been moved
- Move the beartrap dropping code to the character or monster escape functions
- Make it so that when downed, snared, or beartrapped, walking into a monster will attack it
- Pressing tab or pausing will still prioritize trying to remove the bad effect. Generally a downed player will want to get up before trying to attack again, so this is the better solution there, and we apply that across the board for consistency
- Fix messaging to stop the trap from closing on monster appendices
- Apply the same fixes to snares
- Add a sound to beartraps
Tab …
=> Beartraps drop properly and don't prevent attack

data/json/techniques.json
Fix bad Zui Quan vector
I backported some updates to attack vectors, but they missed a custom move I'd made. This caused it to throw an error when trying to use it.
"GRAPPLE"->"vector_arm_grapple"
Did the move, no error
=> Fix bad Zui Quan vector

data/json/items/armor/arms_armor.json, data/json/items/armor/hoods.json, data/json/items/armor/legs_armor.json, data/json/items/armor/suits_protection.json, data/json/items/armor/torso_armor.json, src/monster.cpp
Fix chainmail and snares
I forgot to make snares/beartraps drop when a trapped monster died, and also some chainmail pieces were still not properly switching their layer when loosened.
- Traps now go to the monster's inventory when it dies, if it's still stuck.
- Chainmail should work better, and also budget chain/plate lost their STURDY flag.
Seems good
=> Fix chainmail and snares

data/json/body_parts.json, data/json/items/armor/integrated.json, data/json/morale_types.json, data/json/mutations/mutations.json, data/json/obsoletion_and_migration/obsoletion.json, data/json/professions.json, data/json/scenarios.json, src/magic_spell_effect.cpp, src/monster.cpp, src/npc.cpp, src/suffer.cpp
Remove Killer Drive and eye sweat
- Eyes were able to become wet, which didn't do anything because they're unaffected by temperature. This was causing weirdness with the protective lens cbms and probably some integrated mutations as water would get trapped on the BP, unable to evaporate(???).
- Killer Drive was buggy, annoying, and ridiculous.
- Set drench_capacity on eyes to 0. They simply cannot get wet and do not interact with that system.
- Removed killer drive.
- Removed the death row convict profession. If you want to play as a serial killer on death row, just...play as a convict?
- Added some coverage to beaks, switched their material to keratin.
- Moved claws over to keratin.
- Added some coverage to saber teeth and incisors.
- Adjusted thickness to make protection values less …
=> Remove Killer Drive and eye sweat

data/json/effects.json, src/monster.cpp
Fix grab not applying dodge penalties
Grabbing was supposed to apply a -8 dodge penalty to the user (-5 for monsters, who have fewer sources of dodge bonus and cap out at 10) and prevent the victim from dodging at all, however this was found to be not working! The penalty seemed to apply to monsters, but not characters due to DODGE_CHANCE getting enchantified - the dodge_mod json object in effects.json was simply not affecting players.
- Move dodge_mod for grab stuff to a DODGE_CHANCE enchantment. Hardcode (for now) the dodge penalty for grabbing or being grabbed to monsters, as they don't care about that enchantment.
DODGE_CHANCE could be made to work for monsters pretty easily, then that could be jsonized. Monsters with multigrab are currently sitting at -5 even with two grabs going. …
=> Fix grab not applying dodge penalties

src/character.cpp, src/creature.cpp, src/line.h, src/melee.cpp, src/monattack.cpp, src/ranged.cpp
Double Z for aim and attack
Tiles are not cubes, they're rectangular prisms - a Z level is roughly twice as a tile is wide or long. As such, ranged attacks should consider Z levels 2 steps, not one. 
- Adds a new function, trig_dist_z_adjust, that multiplies Z distances by 2. Apply this function to all targeting, aiming, and in-range checks. This makes it harder to shoot up or down and makes diagonal attacks across Z levels impossible without something like a pike.
- Gives monster special attacks the same treatment.
- Removes the ability to learn anything from reach attacks entirely, as apparently heavily nerfing it was not enough to dissuade people from abusing it.
- Adjusts is_adjacent() to reject vertical diagonals.
- You can still attack enemies below you on stairs, that's fine.
- Z …
=> Double Z for aim and attack

data/json/mapgen/drive-in_theater.json, data/json/mapgen/farm.json, data/json/mapgen/farm_dairy.json, data/json/mapgen/farm_dairy_2.json, data/json/mapgen/farm_horse.json, data/json/mapgen/farm_stills.json, data/json/mapgen_palettes/farm_lots.json
Reduce farm plants and drive-in cars
- Drive-ins could be empty or full. When full, they were completely stocked with like 30 near-pristine cars. This cuts that WAY down so you're lucky to get a couple.
- Traveling cross-country recently, I realized that a lot of farm fields still haven't been planted, and it's currently May. IRL, most American farms do their planting in June to maximize growth in the warmest part of the year. The game canonically starts in April, so there shouldn't be ANYTHING planted. Still, I think it'd be weird to have farms in the game with no crops ever, so I simply reduced the seeds some more. Maybe some early planting got done, or what's growing now are from seeds left in the fields last fall.
- Reduce drive-in cars by a lot
- Cut farm plants by about half
- …
=> Reduce farm plants and drive-in cars

data/json/hobbies.json, data/json/mutations/mutations.json, data/json/obsoletion_and_migration/obsoletion.json, data/json/profession_groups.json, data/json/professions.json, data/json/scenarios.json
Hobby and Profession cleanup
- There were a bunch of dumb redundant hobbies
- There were a bunch of silly or pointless professions
- This made chargen more confusing than it needed to be and took the focus off of customization
- Remove all hobbies that are just skills
- Collapse all the MA hobbies into a weapon and an unarmed hobby
- Clean up and condense the starting hobbies
- Remove a bunch of redundant, extraneous, or silly professions.
- Professions need to be a source of gear and starting vehicles, rather than insane skills.
- Hobbies should be a source of proficiencies and addictions.
- Game Master and Skater need to be proficiencies.
Loads and runs, chargen looks good, NPCs aren't exploding. Old saves might throw an error but you can just skip it.
=> Hobby and Profession cleanup

src/melee.cpp
Fix stray debug message
Fix a random weird message popping up when attacking.
I left a message that said "wearing weapon" in the melee code by accident. I was just checking something w/r/t weapon wear during combat. This removes it.
=> Fix stray debug message

data/json/itemgroups/Clothing_Gear/clothing.json
Remove NV and IR goggles from firefighter zeds
Firefighter zombies had NV and IR goggles. While some specialized firefighters do carry these items in specific locations (ie Navy fire controlmen), they're not a normal piece of kit for the guys at your local station. Additionally, their drop chance even at 1% wound up being way too high, so firefighter zombies became the most reliable place to get these items.
Remove them from firefighter zeds.
=> Remove NV and IR goggles from firefighter zeds

src/martialarts.cpp, src/melee.cpp, src/player_display.cpp
Check for worn status on PROVIDES_TECHNIQUES
Items that have PROVIDES_TECHNIQUES were granting their techs if they were in your inventory at all. This is inappropriate, they're supposed to only work when worn.
- Add a check for whether the item is worn.
- Spawn with bagh nakhs. Wear them, claw stuff.
- Put them away. Do not claw stuff.
- Drop them. Do not claw stuff.
- Mutate fangs. Bite stuff.
- All seems good.
This should not impact weapon techs (IE precise strike)
=> Check for worn status on PROVIDES_TECHNIQUES

src/map.cpp
Backport 79026 - Fix bad roof replacement
There was a bug where some terrains (mostly fence posts) were not turning into floors when destroyed above a roofed tile.
Switch the check for the tile under the fence from WALL to SUPPORTS_ROOF
=> Backport 79026 - Fix bad roof replacement

src/activity_handlers.cpp, src/creature.cpp, src/map.cpp
Fix 2 Z level bugs
1) Shockers were able to shoot you through the floor if they were directly below you. This was an oopsie on my part when I redid the adjacency checks.
2) NPCs were ascending through solid floors even if no stairs etc existed to help you craft if you were above them (or descending if you were below). This was a DDA bug, as clear_path() was not properly considering the fact that human beings cannot float directly upwards through solid roofs/floors.
1) Fix creature::is_adjacent()
2) Add a bunch of checks to clear_path() now looks for stairs or whatever to get up and down floors, rather than just phasing through them.
=> Fix 2 Z level bugs

data/json/effects.json
Reduce heat slowdown
Temperature is mad fucked up, but there's only so much I can do about it without having to rewrite the whole thing. One major issue is that the heat slowdown effect seems really drastic, with the player losing 10% of their speed on a typical summer day and that easily jumping to 30% on a bad one. Given that we're already penalizing their armor, making them sweat buckets, etc. etc., let's chill out on the heat thing eh?
Previously: Heat slowdown was 10, 30, and then 50
Now: Heat slowdown is 5, 15, and then 35.
- Rewrite the entire system to be less stupid (eventually!)
- Add fans and portable AC units (that's coming soon)
Loaded in, set temp to 95 degrees, saw a speed loss of 5. Yeah 95 Fahrenheit is pretty spicy but you have a lot of problems in that kind of weather …
=> Reduce heat slowdown

src/character.cpp, src/scenario.cpp
Fix stray backgrounds
Some of the adult_basic backgrounds (IE Driver's License) were not properly being filtered out of the profession list in cases where the chosen scenario had no professions defined.
- Add && !is_hobby() to the function that populates the list when no professions are defined for the scenario.
- Fix a random typo in a comment in a totally unrelated file
Works
=> Fix stray backgrounds

data/json/items/melee/swords_and_blades.json, data/json/items/resources/misc.json, data/json/martialarts.json, data/json/recipes/armor/arms.json, data/json/techniques.json, src/melee.cpp
Martial Arts bugfixes
- Fior di Battaglia had an exploit where its on-move debuff was not persisting, so you could get out of it by switching to another MA and then back to Fior
- Pankration's grabthrow was obsoleted by, uh, grabbing and throwing
- Player knockbacks were not releasing the target from grapples, causing some teleportation
- Ninjutsu wasn't able to use wakizashi
- Ninjutsu Escape Plan was adding 10% speed, not 10 move speed like it said
- Ninjutsu Escape Plan - Flat bonuses are actually not possible, so it now adds 10% move speed
- Adjusted some MA buff texts for clarity
- Turned down damage on Ninjutsu Takedown (why was it so high?!)
- Removed Grab and Throw from Pankration
- Made Fior's on-move debuff persist if you switch styles
- Player knockbacks now properly check if …
=> Martial Arts bugfixes

data/json/items/armor/suits_clothes.json
Fix long-sleeved jumpsuits more
Long-sleeved jumpsuits have variants. The XL and XS didn't have any defined, but they used copy-from so they didn't have names in the crafting menu.
Give them the generic jumpsuit variant, same as you'd see when crafting the normal one.
PREFIX_XL/XS doesn't apply to variant names, which is a problem that ought to be fixed.
Looks good
=> Fix long-sleeved jumpsuits more

data/json/recipes/practice/ranged.json
Intermediate archery training autolearn 2->3
Move the intermediate archery training recipe's autolearn to 3 archery. You can get it from a book at 1 rank which is ideal, but you can still figure out basic archer's form on your own if you have some significant self-training.
=> Intermediate archery training autolearn 2->3

data/json/techniques.json
Minor MA tweaks
Fine-tune some martial arts stuff
- Eskrima is all rapid attacks. It was also giving some +damage, but given that rapid attacking is already a damage increase, this is not especially appropriate, so the damage buffs were mostly removed.
- Increased Ninjutsu's assassinate from 1.33 to 1.5x damage boost. It's really meant to be doing a significant amount of damage.
- Removed some of the damage boost from dragon tail and dragon claw. They still retain a 1.2x boost, but the MA is supposed to be going for dragon strike as a finisher.
- Added cut/stab to dragon claw, as it's a claw attack and the user may very well have claws.
- Per a suggestion on the discord, adjusted tiger claw. It now confers a slightly larger damage buff than dragon palm (1.33x vs 1.25x) and instead of the …
=> Minor MA tweaks

data/json/obsoletion_and_migration/obsoletion.json
Remove obsoleted professions
I changed around some of the backgrounds you start with at chargen (The ones like Driver's License and stuff). A few got deleted. I stuck them in an obsoletion file and the game decided to populate the list at chargen with them.
Delete them. Perhaps there's a proper way to obsolete professions, but I wouldn't know. Enjoy your error messages! (press i to skip them)
=> Remove obsoleted professions

data/json/mutations/mutations.json
Alongside the removal and rebalancing of indefatigable and the other stamina traits from character creation into only being accessible by mutation, its opposite counterpart languorous was also removed. I feel its removal was unnecessary as the handicap both added a level of difficulty that encouraged more thoughtful and strategic play, and on a personal note I felt it represented my own mitochondrial myopathy and similar genetic metabolic disorders well. 
To restore this trait to its previous state.
Adding back the tag "starting trait: true"
Rebalancing the old trait further or creating a new trait, both felt outside of scope and reasonableness for a simple change to someone else's project in its early stages.
Loaded up, Languorous addable on character …
=> Revert Chargen Languorous Removal

data/json/mutations/mutations.json
Fix bendy and echo, reduce dodge buffs
- Bendy limbs was decreasing rather than increasing dex.
- Way too many mutations were giving massive dodge buffs. Like +3s and stuff, and you could get several of these at once.
- Dead code related to CHITIN_FUR3 still existed.
- Echolocation had too short of a radius. This was because it used to be able to see through glass and needed to be limited, but it was too short to be super useful, and that wasn't a proper fix anyway.
- Echolocation radius +6
- Subaquatic sonar radius +4
- Delete CHITIN_FUR3 hardcoded effect
- Reduce all tail-based dodge chance bonuses to +1
- Remove +2 dodge chance bonus from tiny. Small gets +1, tiny gets +1, diminutive gets +2
- Bendy limbs dex-1 -> dex+1
=> Fix bendy and echo, reduce dodge buffs

data/json/items/melee/knives.json
Give knives throwing damage
Throwing damage was previously set on only a few knives. I removed it, thinking this was unnecessary, but it turns out they do like none without it, so I re-added it. In the process, I gave a bunch of knives that make sense to throw some damage. Now you can throw steak knives and stuff.
=> Give knives throwing damage

src/item.cpp, src/item.h
Fix OSX build
OSX build no work
Remove some orphaned DPS code that was breaking the OSX build.
=> Fix OSX build

data/json/effects.json, src/character.cpp, src/character.h, src/melee.cpp
Missing a reach attack while unstable can make you stumble
- Work toward re-enabling learning on reach attacks by adding reasonable drawbacks and consequences.
- Unstable footing (aka bouldering) is an existing effect granted by certain terrain. This effect now presents an additional hazard: missing an attack while standing here now poses a significant threat of making the character stumble.
The chance is based on strength versus weapon weight, the DEFT/CLUMSY traits, balance and footing scores, dexterity, athletics, GASTROPOD_BALANCE, WEB_WALKER with webs present in the tile, LEG_TENTACLE_BRACE, the presence of sludge in the tile, the presence of slippery substances (like bile) in the tile, and more. BIRD_LEGS, LEG_TENTACLE_BRACE, SCUTTLE, and GASTROPOD_BALANCE additionally prevent the …
=> Missing a reach attack while unstable can make you stumble

data/json/items/ammo/shot.json
Increase birdshot and beanbag recoil
A while back I buffed birdshot. Part of the buff was reducing its recoil. Unfortunately the game infers pressure from recoil and this was causing some shotguns to experience a very high number of failures to eject when using birdshot.
Recoil 800 -> 2000. Ditto for beanbag rounds. I was gonna do 1500, but the base recoil needs to be high enough that derived recoil on IE black powder rounds needs to be enough for the gun to eject properly. 2000 is still substantially lower than buckshot.
Loaded these bad boys into a Tavor and went to town.
=> Increase birdshot and beanbag recoil

src/iexamine.cpp, src/melee.cpp, src/pathfinding.cpp
Fix trading segfault
- The game was segfaulting in the trade window
- melee_value() needed to be rewritten a bit more carefully.
Loaded in, made an NPC friend, traded with them, saw they were assessing values on weapons. 
Assessments still aren't very good and shouldn't be used in place of what the player wants their party members to do, but I'll get to that later. This is just a quick fix.
=> Fix trading segfault

data/json/bionics.json
This adds the flags for BIONIC_TOGGLED & BIONIC_SLEEP_FRIENDLY to the recycler unit CBM. 
You should be able to sleep without a warning. And it is a toggled CBM.
This adds the flags for BIONIC_TOGGLED & BIONIC_SLEEP_FRIENDLY to the recycler unit CBM. 
You should be able to sleep without a warning. And it is a toggled CBM.
Flags added
No alternatives considered
Runs fine in game, no warning before you try to sleep with this CBM active.
=> Update Recycler CBM to be sleep friendly

src/map.cpp
Once again I have left a debug message in
Debug message left in map::shoot()
remove
=> Once again I have left a debug message in

data/json/recipes/armor/suit.json, data/json/ui/lighting.json, src/melee.cpp
Rework vision widget
There has always been a widget called Lighting on your sidebar and it has always been lying to you. That widget has NEVER said what the light level is. What it has always said is how well _you_ can see.
Different people have different vision levels, even in the same lighting. Some people have high perception, or night vision goggles, or mutated Gollum eyes. This meant that this widget was never reliably telling you what the lighting in your tile is, and that led people to incorrectly assume that it means how well others can see you, not how well you can see.
Rename Lighting->Vision
Fix a random unrelated json error.
Rename levels and add more of them to more accurately describe the situation. No matter what your night vision capabilities are like, you can now trust …
=> Rework vision widget

src/character.cpp
Fix autoattack reachability check
Autoattack (pressing tab) runs a check to determine if any targets are in range of the player's weapon. This check fails if a monster is climbing on a chfence, even if that fence is adjacent to the player, because the game knows that impassable tiles block attacks if they're not THIN_OBSTACLE and the character is not wielding a weapon with the SPEAR flag. That's fine for reach attacks, but not adjacent ones, as a creature occupying a chain link fence tile is presumed to be halfway over it, and thus hittable from both sides.
- Add a quick check that always considers impassable tiles valid for attacks if they're adjacent to the character.
Spawned a guy, spawned a feral, let feral climb fence, punched feral
=> Fix autoattack adjacency check

data/json/vehicleparts/manual.json, data/json/vehicleparts/vehicle_parts.json, data/json/vehicleparts/vp_flags.json, src/vehicle.cpp
Make hand paddles and sails only work in water
Hand paddles need to output a lot of power to make boats move at a reasonable speed. That's fine in water, but they worked on land, too, and were better than pedals or hand rims. That doesn't make any sense!
Sails and hand rims now only work if the terrain tile they're in has the SWIMMABLE flag. That's most water and water-like substances in the game.
It is kind of weird how engine power just directly provides propulsion to boats. Makes sense for paddles and sails, but not for foot pedals or a gas engine. We don't have any way to link parts up in separate tiles yet, but if we did we could make proper swan boats or outboard propellers.
- Spawned a wheelchair. It drove on the road OK.
- Took its hand rims off and applied hand paddles. It could …
=> No sailing on dry land

data/json/npcs/robofac/robofac_intercom/robofac_intercom.json
Hub 01 buys (most) artifacts
- Artifacts are often really disappointing due to their randomness
- Some items (spiral stone, petrified eyeball) seem important but don't do anything
- Hub 01 is being reworked later, and they'll eventually only buy this kind of stuff (or their coins). They'll still sell most of the stuff they sell now
- Add a bit of dialog with the Hub 01 intercom once you unlock the ability to trade. This explains that they'll pay good money for artifacts.
- Add all the "altered X" artifacts (hawaiian shirt, bakelite phone, etc) to their purchase list.
- Add the monolith disc and brick (are those even accessible in TLG?).
- Add the petrified eye and spiral stone to their purchase list. They pay decent money for the eye and not much for the stone, as the stone is easier to …
=> Hub 01 buys (most) artifacts

data/json/items/armor/arms_armor.json, data/json/items/armor/brigandine.json, data/json/items/armor/gambesons.json, data/json/items/armor/integrated.json, data/json/items/armor/legs_armor.json, data/json/items/armor/suits_protection.json, data/json/items/armor/torso_armor.json
Remove BLOCK_WHILE_WORN
Due to a confusing code comment, I misunderstood how BLOCK_WHILE_WORN works. If you have the flag on a piece of armor (any armor!) it allows you to do arm blocks as if you had them via a martial art, but with a +2 bonus. It feels like a kludged attempt at including shields, and we're not there yet. We'll get there, just, not yet.
Given that this devalues martial arts, it shouldn't go on anything. It especially shouldn't go on stuff that doesn't cover your arms, but that's sort of beside the point. Yes, it makes sense that if you have metal bracers on you might block attacks with them...which is already what you'll do if you have a martial art that has an arm block technique!
- Remove from all items.
I could maybe see a case for this flag on like...an artifact? But …
=> Remove BLOCK_WHILE_WORN

src/character.cpp, src/handle_action.cpp
Fix releasing grapple
Pressing G to release a grapple wasn't properly getting rid of all the effects.
Fix it and make sure it does grab_1.clear()
Multigrabs will require a thing that checks to make sure you're releasing the right enemy. I considered adding grab_strength to the grabbing effect (as intensity) but I think it's easier to just track grab_1.victim or whatever.
Grabbed a debug monster, released it, walked away no problem. Grabbed it, dragged it, threw it, everything worked.
=> Fix releasing grapple

data/json/monster_special_attacks/feral_weapon_attacks.json, data/json/monsters/feral_humans.json, data/json/monsters/nether.json, data/json/monsters/zanimal_upgrade.json, data/json/monsters/zed-classic.json, data/json/monsters/zed_explosive.json, data/json/monsters/zed_misc.json
Balance updates for zombies, regenerators, and ferals
Patches several exploits and areas where the game was not giving appropriate pushback.
- Ferals can now bite things when they're grabbed. There's a 10 second cooldown on this so it's not extremely dangerous, but it's still a wrinkle that makes grabbing them a little more balanced.
- The existing feral grapple attack now uses the feral's melee skill instead of a set accuracy of 3.
- A few zombies have a few more points of fire armor.
- Zombie hunters and predators will now avoid falls and fire. These are meant to be capable, intelligent (in terms of predation) hunters rather than an unruly mob like the others.
- Thorny shamblers and thorny moose shamblers now avoid falls and fire. The triffids parasitizing them are able to exert limited …
=> Balance updates for zombies, regenerators, and ferals

build-data/osx/Cataclysm.sh
Update OSX shell script to fix mac curses
Fixes #900 
Fingies crossed!
=> Update OSX shell script to fix mac curses

src/activity_actor.cpp, src/game.cpp, src/handle_action.cpp
Backport 76262 - fix pulping acid corpses
A backport broke this, so let's backport the fix!
=> Backport 76262 - fix pulping acid corpses

data/json/mapgen/motel.json
Fix solar panel windows on 2f motel
The 2f motel was needlessly using the roof palette, which used the same mapgen character for solar panels as the motel was using for windows.
Remove the roof palette and manually define its tiles.
No solar panels.
=> Fix solar panel windows on 2f motel

data/json/requirements/toolsets.json, src/requirements.cpp
Backport 77114 - Fix 00 shot crafting (Requirements warn if loading components as tools)
Shotgun shell crafting was broken.
=> Backport 77114 - Fix 00 shot crafting (Requirements warn if loading components as tools)

data/json/martialarts.json
Need a martial art to arm/leg block
For some reason, "no style" gave you arm block at 1 skill. This meant that you could turn off your martial arts to be great at blocking attacks, but half the martial arts would disable this ability. That...doesn't really make any sense, and was likely unintentional.
No more arm block on no style or force unarmed. Use a martial art or a weapon!
=> Need a martial art to arm/leg block

data/motd/ar.motd, data/motd/cs.motd, data/motd/de.motd, data/motd/el.motd, data/motd/en.motd, data/motd/es_AR.motd, data/motd/es_ES.motd, data/motd/fil_PH.motd, data/motd/fr.motd, data/motd/ga_IE.motd, data/motd/hu.motd, data/motd/id.motd, data/motd/it_IT.motd, data/motd/ja.motd, data/motd/ko.motd, data/motd/nb.motd, data/motd/pl.motd, data/motd/pt_BR.motd, data/motd/ru.motd, data/motd/tr.motd, data/motd/uk_UA.motd, data/motd/zh_CN.motd, data/motd/zh_TW.motd
Remove beta warning in motd
There were some old beta warnings in the message of the day. We're not in beta anymore!
=> Remove beta warning in motd

src/ranged.cpp
Fix wont_train_marksmanship
The change to ranged.cpp that was supposed to accompany #939 got lost in the shuffle
Add it
Werks
=> Fix wont_train_marksmanship

src/item.cpp
Backport DDA 77551 - Check for nullptr before calling
Fixes a bug with opening the eat menu around some items.
=> Backport DDA 77551 - Check for nullptr before calling

data/json/items/melee/bludgeons.json
Fix nunchaku length
Nunchaku were 160cm long lol
Shorten them to 33cm
=> Fix nunchaku length

src/path_info.cpp
Silo OSX user data from other forks
The OSX application data's default path was shared with Cataclysm DDA, we don't want that as it makes it awkward to try to play both games.
=> Silo OSX user data from other forks

data/json/furniture_and_terrain/terrain-walls.json, src/map.cpp
Nerf tree-felling a bit
Felled trees were punching through solid concrete. This was stupid.
Reduce the number of bashes a felled tree attempts from 5 to 4, randomize the damage a bit, and reduce its maximum by 1/6.
There's a lot more to do here. This shouldn't really work very well at all honestly, falling trees damage houses, they don't cleave them in half IRL. There's also an issue where the bash doesn't affect furniture. Does it affect creatures? Vehicles?
Felled a tree. It went through drywall. Fine.
=> Nerf tree-felling a bit

src/game_inventory.cpp, src/item.cpp, src/item.h
Fix armor display bugs
- #952 broke armor display.
- Acid and fire resistance were always displaying wrong in the (W)ear menu.
- Return the mistakenly removed code.
- Remove fire and acid protection from the (W)ear menu.
I would rather have the values display properly, but game_inventory.cpp is set up to take a simple average of the protection values and isn't able to handle the more complex material layer evaluation that fire and acid do in TLG, so for now it's best to simply remove them. They dispaly properly in the examine window.
=> Fix armor display bugs

src/anatomy.cpp
Silence post-death error messages
The code in anatomy.cpp that determines which part you get hit in does so by process of elimination, excluding 0 HP parts and parts the enemy can't reach, etc. This has always worked fine, except when I added webbed hands, characters went from having 0-13 out of 13 body parts to having 0-13 out of 15 body parts (this might actually be 20 if we count bird/bat wings and gastropod foot), since no one has both hands and webbed hands. This meant that dead characters had -2 or fewer available body parts, which the code doesn't know how to deal with.
Check if the character is dead and exit early if so. This may not be a perfect solution, as the day may come when we have enough variant body parts that it may be possible for a living character to get a negative …
=> Silence post-death error messages

src/npc.cpp
Clamp NPC starting kcal a bit tighter
NPCs were frequently (like 5-10% of the time!) spawning emaciated. This was really onerous to deal with and not very intuitive, partly because NPCs weren't letting the player know they were starving and partly because with NPC needs disabled, most people aren't aware that NPCs can still eat if they need to.
Clamp the initial starting kcal to ~50,000 to ~450,000. This still results in people who have higher or lower body fat, and still trends toward leaner as time goes on, but will stop short of handing you a recruitable skeleton.
Starvation is a reasonable issue and some NPCs should start out emaciated, but they ought to be assigned special quests to bring them food. It should also be easier to fatten them back up, and to know when they need help with …
=> Clamp NPC starting kcal a bit tighter

data/json/body_parts.json, data/json/items/armor/cloaks.json, data/json/items/armor/integrated.json, data/json/mutations/mutation_limbs.json, src/character_armor.cpp, src/character_attire.cpp, src/item.cpp, src/item.h
Make armor work and display on mutated parts
Mutated parts (bird/bat wings, webbed hands) were added in using the semi-finished limb system, but several features weren't functioning properly, most of them related to armor.
- Make armor now only display parts and subparts which you have in all of its menus.
- Make armor coverage, warmth, etc. apply properly to nonstandard parts.
- Make it impossible to wear armor for parts which you do not possess.
- Update feathers, lightfur, and fur to have explicit coverage for the wings.
- Update all cloaks to have explicit coverage for the wings.
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa this took forever
Wear mittens, mutate webbed hands, wear mittens. Works.
Wear a cloak, mutate feathers, mutate wings, …
=> Make armor work and display on mutated parts

data/json/items/armor/arms_armor.json, data/json/items/armor/boots.json, data/json/items/armor/cloaks.json, data/json/items/armor/coats.json, data/json/items/armor/hats.json, data/json/items/armor/legs_armor.json, data/json/items/armor/suits_clothes.json, data/json/items/armor/suits_protection.json, data/json/items/armor/undergarment.json, data/json/recipes/armor/feet.json
Encumbrance tweaks
Correct various encumbrance issues and errors
- Long underwear encumbrance now matches union suit.
- Added some encumbrance to belly wraps and other items which had none.
- Reduced jean jacket torso encumbrance slightly. Sleeve encumbrance stays the same - this is heavier weight denim than jeans, but that matters a bit less on the torso.
- Reduced most cloak encumbrance slightly.
- Increased chitinous armor encumbrance slightly.
- Increased biosilicified chitinous armor encumbrance slightly.
- Reduced chitin arm guard coverage slightly.
- Renamed chitin leg guards to chitin greaves.
- Decreased chitin greaves coverage slightly.
- Kercheif -> kerchief.
=> Encumbrance tweaks

data/json/mutations/mutation_techs.json
Balance "increase weighting of Ursine Muzzle bite attack"
The bear bite attack is weighted very low. At -4 it's only possible 25% of the time, and that 25% of the time it still might not happen if there are other eligible techniques. Unlike other mutation lines, Ursine mutants also lack a natural stance option to deliberately increase the likelihood of using the technique. Since the technique is _also_ conditional on the opponent being Downed, and Downing usually relies on RNG to begin with, that means you very rarely see it even if you're actively trying to play towards it.
Increase the weighting to -2, . This makes both mechanical and intuitive sense to me; I see it as the animal instincts kicking in when you see a Downed enemy and compelling you strike. It also matches the natural …
=> increase weighting of FANGS_BITE_MUZZLE_BEAR

data/json/items/armor/boots.json, data/json/items/tool_armor.json
Earplugs work again
Earplugs weren't working because of the mutation part changes.
Give them coverage and some flags so everyone can wear them.
=> Earplugs work again

data/json/mutations/mutations.json
Roadrunner mutation requires you to stand
The roadrunner mutation was making birds crawl super fast.
The mutation only works if you are walking or running.
=> Roadrunner mutation requires you to stand

data/json/enchantments.json, data/json/mutations/mutations.json
Fix mutant move costs and other things
- Bat wings needed limbifying
- Many mutation bugs
- Move cost inconsistencies and cleanup
- Limbify bat wings
- Ursine gets digitigrade legs
- Batrachian gets Very Ponderous
- Gastropod Foot redone
- Most move cost mutations don't affect you when you're prone
- Feline gets fleet-footed
- Fix gastropod bug that was taking their foot away
- Fix various other issues
**Move Costs**
These are all on fresh survivors. The human had tough feet. No weapons were wielded, so these are quadrupedal values for relevant mutants.
Human: Run 50, Walk 100, Crouch 200, Prone 600
Beast: Run 40, Walk 110, Crouch 97, Prone 575
Feline: Run 31, Walk 87, Crouch 87, Prone 533
Lupine: Run 38, Walk 110, Crouch 91, Prone 567
Ursine: Run 57, Walk 147, Crouch 164, Prone 759 …
=> Fix mutant move costs and other things

src/character.cpp
Silence the other wacky body part error
An error message in apply_damage() was fixed back in #959 but I missed one in dealt_damage_instance().
- Change the error to a quieter debug message.
- Prevent the error from happening when the character is dead (which is when we were seeing it) by exiting dealt_damage_instance() early if the character is_dead_state(), as was done with apply_damage() in #959
=> Silence the other wacky body part error

data/json/items/armor/legs_armor.json
Fix some leg armor encumbrance
This stuff needs a full audit, but in the meantime here are a couple of fixes.
- Increase encumbrance on jeans_mod and motorbike_pants
=> Fix some leg armor encumbrance

data/json/items/armor/legs_armor.json, data/json/items/armor/legs_clothes.json
Shrink all pants pockets a lot
All pants were able to hold ridiculous amounts of stuff, you could fit like six liters of stuff in a pair of jeans. No.
=> Shrink all pants pockets a lot

data/json/furniture_and_terrain/terrain-doors.json, data/json/furniture_and_terrain/terrain-walls.json, data/json/items/armor/jewelry.json, data/json/items/armor/legs_clothes.json, data/json/items/armor/misc.json, data/json/items/armor/torso_clothes.json, data/json/monsters/insect_spider.json, data/json/mutations/mutations.json, src/character.cpp, src/character_inventory.cpp, src/item.cpp
Slightly adjust ant skill hp and armor
Ants are weird. They were made a long time ago when copy-from was new I guess, and there are a lot of what seem to be mistakes in their stats.
This is a quick fix, not a full audit, but it should be an improvement:
- Reduce soldier ant melee skill to 5
- Increase soldier ant damage from 1d8 to 2d6
- Increase ants' cut damage
- Reduce ants' armor, especially ballistic, in line with how chitinous armor works
- Increase HP for most ants
- Increase grab strength of soldier ants
- Adjust descriptions to make the sizes of these ants more clear
=> Slightly adjust ant skill hp and armor

data/json/items/armor/bespoke_armor/custom_bodysuits.json, data/json/items/armor/suits_clothes.json
Shrink pockets on bodysuits
#994 shrank pants pockets. Bodysuits are not safe either.
=> Shrink pockets on bodysuits

data/json/obsoletion_and_migration/migration_items.json, src/magic_spell_effect.cpp
Fix spell dodge messaging bug
Fix a messaging bug with dodgeable spells which sometimes throws errors.
Special case monster dodge messaging, add a check for invisible monsters, use add_msg_if_player_sees() for the dodging monster.
=> Fix spell dodge messaging bug

data/json/obsoletion_and_migration/migration_items.json
Migrate the homemade halfpike
The homemade halfpike was removed but not migrated, resulting in errors in old saves which contained it.
Migrate it.
=> Migrate the homemade halfpike

src/construction.cpp
Remove vestigial construction_scaling code
Some vestigial code was causing an error
Removed
Press *, no error
=> Remove vestigial construction_scaling code

data/json/furniture_and_terrain/terrain-flora.json
Fix hemlock harvested name/desc
Hemlock tree was named "pine tree" when harvested
Fix name/desc
=> Fix hemlock harvested name/desc

src/character.h, src/creature.cpp, src/creature.h, src/melee.cpp, src/monster.cpp, src/monster.h, src/newcharacter.cpp, src/player_display.cpp
Fix dodge bonus display
- Critfails were sometimes showing in the dodge readout due to living in creature::get_dodge() for simplicity's sake.
- Dodge bonus wasn't showing under perception in charge.
- "Dodge skill" it's literally not.
- Dodge bonus is a float but was only displaying the int in chargen.
- Display dodge bonus as a float in chargen.
- Edit the text to say Dodge bonus and not Dodge skill.
- Add it to the perception readout.
- Add a bool that lets us optionally check get_dodge() without the possibility of a critfail, and use it in newcharacter and player_display.
The chargen readout is still showing dodge bonus with the darkness penalty. Not a big deal, but it'd be nice to be able to fix that.
Loads, runs, looks good. Tried chargen, tried @, got in some fights. All good.
=> Fix dodge bonus display

data/json/items/armor/coats.json
Make Hakama worn on the Outer layer
Better reflect reality where Hakamas are often worn over kimonos but doing so in game causes conflic and extra encumbrance. It also would fix the Urban samurai starting gear having conflicting gear.
Added the Outer flag to the Hakama in coats.json
Game launches and runs fine and the item is indeed now worn on the Outer layer. The Urban samurai starting clothing no longer has conflicts.
=> Make Hakama worn on the Outer layer

src/activity_handlers.cpp
Backport 77906 - fix pickaxe error message
Pickaxe was always displaying an error message about expiring when used.
Backport!
=> Backport 77906 - fix pickaxe error message

src/character.cpp, src/melee.cpp, src/newcharacter.cpp
Buff perception and improve chargen
- With the NV trait gone and weather often worse than DDA, night time was becoming painful.
- Chargen helptext is still sort of sloppy.
- Buff the NV bonus from perception by 7%.
- Helptext in chargen now mentions crit rates for dex/per, mentions stab weapon lodging, shows NV bonus, displays persuasion and deception as distinct scores.
Made a guy, looked at chargen, messed with night vision radii, looks good.
=> Buff perception and improve chargen

data/json/items/armor/coats.json
Remove extra coverage for torso from cutting off the sleeves.
To make extra leather not magically appear on the chest because you cut off the sleeves
Make the sleeveless longcoat also 95 torso coverage
not doing anything
The coverage is changed
none
=> Sleeveless Coat Audit

src/catacharset.cpp
Possibly fix mac build
Codecvt is deprecated in the latest macos compilers, I guess, so while it fixed the Steam linux build, it broke mac.
Blindly make a change and see if that breaks the other stuff.
=> Possibly fix mac build

.github/workflows/msvc-full-features.yml, .github/workflows/release.yml
Fix MSVC builds, maybe
Windows-2019 reached end of life back in June. We're told to use Windows-2022 instead. Well, let's see if that works.
=> Fix MSVC builds, maybe

data/json/monsters/defense_bot.json, data/json/monsters/drones.json, data/json/monsters/feral_humans.json, data/json/monsters/insect_spider.json, data/json/monsters/jabberwock.json, data/json/monsters/kraken_spawn.json, data/json/monsters/lab_security_drones.json, data/json/monsters/robofac_robots.json, data/json/monsters/utility_bot.json, data/json/monsters/zed-classic.json, data/json/monsters/zed_skeletal.json, data/json/monsters/zed_soldiers.json, src/magic_spell_effect.cpp, src/map_field.cpp, src/monster.cpp
Adjust hazard damage for monsters
Monsters don't have body parts, instead using a single pool of HP. This makes them effectively much less durable than characters, something that needs to be accounted for. Additionally, they were basically all defenseless against acid unless they had the ACIDPROOF flag.
- Fire does less damage to monsters. It's still pretty lethal to your typical zombie, but they don't instamelt in areas where a human could jog through and come out merely singed.
- Falls do more damage to monsters. They were getting the full benefit of their bash armor, and the base damage was just too low compared to how badly they mess up characters, damaging every body part and all.
- Acid armor now reduces the duration (and therefore the intensity) of the corroding effect when it's …
=> Adjust hazard damage for monsters

data/json/items/gun/8x40mm.json, data/json/items/gun/ups.json, src/game.cpp, src/game.h, src/handle_action.cpp
Move weather animation to its own function and fix flicker
- Weather was being animated in handle_action, inside a ginormous function that was about waiting for player input. This meant it wouldn't animate except when the game was waiting for you to push a button.
- Move it to its own function in game(), which is called both by draw() and during get_player_input, so it animates while idle but doesn't vanish while driving etc
=> Move weather animation to its own function and fix flicker

src/catacharset.cpp, src/crafting.cpp
Guard against incorrect depression craft adjustments
#1043 added a way to clamp crafting speed penalties from morale for some crafts, but failed to guard against clamping morale values when they were above its value. Whoops.
Check before clamping.
=> Guard against incorrect depression craft adjustments

src/map.cpp
Backport 77805 - Ensure crushed characters are fetched from the correct location
Fixes some weird messaging about getting buried under rubble or falling off ledges despite being nowhere near them.
=> Backport 77805 - Ensure crushed characters are fetched from the correct location

data/json/items/gun/38.json, data/json/items/gun/44.json, data/json/items/gun/500.json
Category "Lever Action Reload Flags"
Make it more consistent between lever actions
adds "RELOAD_ONE" flag to lever actions that were missing it.
Game runs, items now behave
=> Add json flags to lever action for reloading

src/sdltiles.cpp
Backport DDA 81560 - Don’t compute the size of far away hordes
Speed up the game by only computing overmap hordes within visual range.
=> Backport DDA 81560 - Don’t compute the size of far away hordes

src/mapgen.cpp
Fix minor rotation error
We don't have the getabs function yet, it's still overloaded in getglobal, but a backport was trying to call it.
Compiles, runs. Mi-go map looks fine.
=> Fix minor rotation error

data/json/overmap/overmap_mutable/farm_mutable.json
Space farms out a bit more
Farms are a bit too common.
This is hard to adjust, but increasing their city distance from 6 to 8 seems to do OK.
Made several worlds, warped around. Isherwoods look fine. Farms are a bit less clustered.
=> Space farms out a bit more

data/json/field_type.json, data/json/items/tool/misc.json, src/iuse.cpp, src/map_field.cpp, src/melee.cpp
Nerf tear gas sprayer and fire extinguisher, buff stun guns
- Fire extinguishers were blinding anything that was capable of being blinded for several minutes.
- Tear gas sprayers and fire extinguishers could be used without wielding them.
- Tear gas was lasting way too long on the map.
- Characters with compound eyes were not immune to tear gas.
- Zombies were a bit too vulnerable to tear gas.
- Stun guns were a bit too weak.
- Cameras were able to blind stuff without appropriate checks, and for way too long.
- Everything was raw RNG
- Stun guns are now more likely to make monsters release grabs.
- Zombies have a chance to not be blinded by tear gas, based on their size.
- Tear gas sprayers and fire extinguishers must be wielded to be used.
- Tear gas sprayers and fire extinguishers will …
=> Nerf tear gas sprayer and fire extinguisher, buff stun guns

src/iuse.cpp
Shut the fuck up I did not fail to put a item in a pouch
- Autoclave pouches were rolling 1d6 and subtracting that from your medical skill. If it got zero, you wasted your pouch and failed to pack it. That is not only annoying, it's quite confusing. 6 is a lot of medical skill, you're telling me skilled professionals still accidentally rip 1/6th of their pouches in half?
- Delete it. If we want to add a skill thing later it'd be related to infection chance or something.
=> Shut the fuck up I did not fail to put a item in a pouch

src/cata_tiles.cpp, src/cata_tiles.h, src/options.cpp, src/sdltiles.cpp
Scale character tiles by size
- You can be the size of a hulk or the size of a toddler in this game, but your tile is always adult human sized. No more!
- Dynamically scaling sizes makes stuff like infrared easier.
- It will probably be broadly useful to be able to dynamically scale other kinds of things too.
- enum_size() characters in one of the nine fucking overloads that tiles are drawn from and use that to give them x/y scaling
- Do the same for infrared tiles.
- Seems to work for all cases I can think of. There are a few tiles in MSX that need fixing. Functionality is iffy outside of MSX, but that's why the option exists.
- A few tiles in MSX (long horns, rabbit ears, maybe one or two others) aren't properly aligned on the 32x32 png and wind up incorrectly offset. This is a tileset …
=> Scale character tiles by size

src/monmove.cpp
Reduce monster movement messaging spam
A trout dives under the water! A trout emerges from the water! how about you shut up
- Disable these messages entirely unless the target is hostile and can see you.
=> Reduce monster movement messaging spam

data/json/mutations/mutations.json, src/catacharset.cpp, src/character.cpp, src/monster.cpp, src/ui.cpp
Update bouldering status per turn
The bouldering effect was not applying when you climbed somewhere, only when you moved. Given that you generally get it while climbing, that needed fixing.
Add a per-turn check for both monsters and characters in process_turn() that applies bouldering if you're up a tree or something.
Went up a tree. Good.
Put a turret up a tree. Good.
=> Update bouldering status per turn

src/iuse.cpp
Fix tactical tonfa and some other hand tools
- Someone got a crash because they were wielding a garbage can with a hacksaw in it (??) and they tried hacksawing some bars.
- Tactical tonfas were broken by #1065 because they were using a virtual item which the player wasn't technically wielding. The odd thing is, there was no reason for them to be doing that.
- You now need to be wielding or wearing your hacksaw, acetylene torch, or prying tool.
- Tactical tonfas just use the regular stun gun function when you zap with them.
- Tactical tonfa works
- Integrated toolset works
=> Fix tactical tonfa and some other hand tools

data/mods/innawood/recipes/recipe_others.json
Fix innawood steel type bug
A recipe backported into innawood was calling for steel types, which we don't have.
no,
=> Fix innawood steel type bug

src/cata_tiles.cpp, src/cata_tiles.h
Fix tile scaling, rename occlusion in comments
Tiles are composed of sprites, that is, individual images which are overlaid atop each other to compose a tile. When tile scaling was added in #1062 I hadn't realized that some character overlays (IE long horns) have different dimensions from the character's body. We were scaling each image individually, but only correcting offsets on a tile scale, meaning that mutations like long horns would be too low if you were big and floating above your head if you were small.
Move the offset adjustments to draw_sprite_at(), meaning they happen per-image according to their individual height and width. This seems to solve all the problems we were having.
=> Fix tile scaling, rename occlusion in comments

data/json/npcs/godco/classes.json, data/json/npcs/godco/members/NPC_Jeremiah_Weaver.json, data/json/npcs/refugee_center/surface_refugees/NPC_Aleesha_Seward.json
Kid NPCs are small
Aleesha Seward, Jeremiah Weaver, and Chloe Taylor are all kids. Aleesha's fourteen, it's not clear what age Jeremiah and Chloe are. I think fourteen ought to be the cutoff for smallness, but it's a good idea to give it to all these NPCs anyway because it's important to their story that they're kids and it clearly signposts it for the player. NPCs standing out from each other more is always nice.
- Change Jeremiah's line about high school to school. Maybe he's a middle schooler, who knows.
- Jeremiah, Aleesha, and Chloe all have the Little trait.
If the game goes on long enough, maybe they ought to grow up. That's a whole other can of worms though.
hahaha they're so tiny
=> Kid NPCs are small

src/character.cpp, src/character.h, src/creature.cpp, src/monstergenerator.cpp
Partially backport 74162 - Character volume
- DDA 74162 moved cramped space calculations to use dynamically derived volume. I am not satisfied with that implementation and we will continue to use size category for now, but it's still useful to be able to figure out what our volume is.
- DDA assumes that different size categories are proportionally 1:1 with medium humans. This is not the case, as children have shorter limbs and larger heads, etc. and the same goes for murine and lagomorph mutants, etc.
- DDA adds your worn equipment to your volume. This is certainly reasonable, but last I checked there were a lot of problems with the approach used, so for now let's just look at the body.
- Use the height limits in size_category_height_limits to get average heights for size categories.
- …
=> Partially backport 74162 - Character volume

data/json/effects_on_condition/nether_eocs/vitrification_effect_on_condition.json, data/json/effects_on_condition/npc_eocs/generic_npc_eocs.json, data/mods/TEST_DATA/effect_on_condition.json, doc/EFFECT_ON_CONDITION.md, src/avatar_action.cpp, src/condition.cpp, tests/eoc_test.cpp
Backport 77941 - EOCs can compare more than one string
Infrastructure, move the hardcoded thing where water washes off the glowing effect to EOC
=> Backport 77941 - EOCs can compare more than one string

data/json/vehicleparts/alternator.json, data/json/vehicleparts/armor.json, data/json/vehicleparts/battery.json, data/json/vehicleparts/boards.json, data/json/vehicleparts/cargo.json, data/json/vehicleparts/combustion.json, data/json/vehicleparts/engineering.json, data/json/vehicleparts/frames.json, data/json/vehicleparts/lights.json, data/json/vehicleparts/manual.json, data/json/vehicleparts/mirrors.json, data/json/vehicleparts/modular_tools.json, data/json/vehicleparts/motor.json, data/json/vehicleparts/rams.json, data/json/vehicleparts/rotor.json, data/json/vehicleparts/seats.json, data/json/vehicleparts/tanks.json, data/json/vehicleparts/utilities.json, data/json/vehicleparts/vehicle_parts.json, data/json/vehicleparts/vp_flags.json, data/json/vehicleparts/wheel.json, src/character.cpp, src/creature.cpp, src/map.cpp, src/monster.cpp, src/npctalk.cpp
Improve eye level/cover calculations with vehicles
- Bicycles were opaque to small characters.
- Vehicle parts weren't boosting your line of sight like furniture does.
- Give a lot of vehicle parts the NO_COVER flag. These parts offer no coverage or concealment. If a vehicle tile is composed entirely of parts with this flag, it is transparent for everyone at all times.
- Make vehicle seats and other parts boost you up in the same way standing on a chair does.
- We still need car seats for mouse mutants.
- Mouse mutants can ride bicycles. This is partially intended as they need to be able to drive the little tricycles and those use the same seat/pedal as a bike. Not exactly sure yet of a proper fix that wouldn't just be installable on a regular bike.
=> Improve eye level/cover calculations with vehicles

src/iuse.cpp
Remove wield requirement for prying for now
fixes #1132 
I made it so you needed to wield or wear prying tools to use them, but that was causing some unexpected behavior because most of the prying code is done in iexamine, and it just tries to pick your best item. It's worth redoing, but for now we can just dump the requirement.
=> Remove wield requirement for prying for now

src/basecamp.h
Fix missing header declaration
Forgot to push
=> Fix missing header declaration

data/json/effects_on_condition/mapgen_eocs/lab_mapgen_eocs.json, data/json/effects_on_condition/nether_eocs/vitrification_effect_on_condition.json, src/teleport.cpp
Backport 77571 and 77622 - EOC and Teleport improvements
Re-implement part of #1149
=> Backport 77571 and 77622 - EOC and Teleport improvements

data/json/mutations/mutation_techs.json
Fix talon kick vector
Talon kick needed its vector. Now it has it.
=> Fix talon kick vector

data/json/itemgroups/main.json, data/json/items/armor/ammo_pouch.json, data/json/npcs/random_encounters/john_bailey.json, data/json/professions.json, data/json/recipes/nested.json, data/mods/innawood/professions.json
Reduce arrows in quivers in itemgroups
There were to much arrow,
By contributing to the project you agree to the term of the license and that any contribution you make will also be covered by the same license.
See http://creativecommons.org/licenses/by-sa/3.0/ for details. -->
=> Reduce arrows in quivers in itemgroups

data/json/mapgen/robofaq_locs/robofac_hq_chunks.json
Remove free guns from Hub01 ancilla bar
The fortress part of the Hub 01 ancilla area had some guns and stuff in the lockers. This was seemingly intended to belong to the mercs there, but it showed up on day 1 before anyone was even in the place, and it wasn't flagged as belonging to them.
Remove it. Eventually I'll nix that whole structure and most of those NPCs will get moved elsewhere and reworked, but for now we can just delete the unaccountable free guns.
=> Remove free guns from Hub01 ancilla bar

data/json/harvest.json, data/json/itemgroups/main.json, data/json/items/armor/ammo_pouch.json, data/json/monsters/mammal.json, data/json/monsters/mutant.json, data/json/monsters/zanimal_upgrade.json, data/json/monsters/zed-animal.json
Add antlers to more zeds and animals
Zombie deer and mooses didn't have antlers! That's no good. Neither did the ungulate mutant.
Give all the zombie deer, moose, reindeer etc. antlers in their harvestry lists. You want to butcher them to get these.
=> Add antlers to more zeds and animals

data/json/mapgen/farm_dairy.json, data/json/mapgen/farm_dairy_2.json, data/json/mapgen/map_extras/military.json, data/json/mapgen/mine/mine_generic.json, data/json/mapgen/movie_theater.json, data/json/mapgen/radio_tower.json, data/json/monstergroups/fungi.json, data/json/overmap/overmap_mutable/farm_horse_mutable.json, data/json/overmap/overmap_mutable/farm_mutable.json, data/json/overmap/overmap_special/specials.json
Further map adjustments
Fix stuff that's always bugged me.
- Space dairy farms and other locations out a bit more.
- Reduce food in movie theaters.
- Improve the military corpses map extra. The corpses are dirty and potentially damaged as you'd expect from guns left in the mud.
- Make the radio tower sniper nest much rarer, change it to be a zombie soldier instead of a pile of clothes.
- Reduce some various other freebies.
- Increase the fodder in farms a bit.
=> Further map adjustments

data/json/npcs/missiondef.json
One of the missions where you gather cattails had dialogue that told you to gather 80 stalks; the actual amount required is 20.
Make the dialogue match the mission requirements.
Change '80' to '20' in the dialogue.
Not sure why there are two almost identical missions for cattail jelly. One of them could possibly be removed. For now I will just correct the typo.
=> Fix minor error in cattail mission dialogue

src/game.cpp
Delete hardcoded leg tentacle bracing effect
There's a stupid hardcoded effect that checks dex and int and can make you randomly stick to the ground when walking around as a cephalopod, with an accompanying spammy message. Cephalopods are already slow as hell, if they need to be slower (and they don't) that could be managed without this bespoke hardcoded thing.
Sinmply,,delet it;
=> Delete hardcoded leg tentacle bracing effect

doc/EFFECT_ON_CONDITION.md, lang/string_extractor/parsers/effect.py, src/npctalk.cpp, src/string_input_popup.cpp, src/string_input_popup.h
Backport 75949 to fix string input issue
fixes #633  I should think.
=> Backport 75949 to fix string input issue

src/item.cpp, src/magic.h, src/magic_spell_effect.cpp
Backport 78332 - Fix ethereal item spells
=> Backport 78332 - Fix ethereal item spells

data/json/items/tool/lighting.json
Remove link from smart lamp for now
There's some weird stuff going on with this item that DDA hasn't solved, and the error messages are annoying.
Remove the link action.
=> Remove link from smart lamp for now

data/json/effects.json, data/json/items/gun/9mm.json, data/json/monster_weakpoints/migo_weakpoints.json, src/creature.cpp, src/monster.cpp, src/monster.h, src/ranged.cpp
A fun combat balance pass
- Creatures are easier or harder to hit in melee based on their size. These numbers were very inflated for tiny and huge creatures, and they were not standardized.
- Mi-go and wasps had an easy time clearing dozens or hundreds of zombies due to how dodge rolls and armor work.
- There were some ongoing issues with HARDTOSHOOT and occupied_tile_fraction.
- Melee to-hit penalties/bonuses for size are standardized, clamped a bit, and slightly randomized.
- Adjusted HARDTOSHOOT, making both tiny and huge creatures slightly easier to hit. HARDTOSHOOT is now equivalent to crouching (a -25% multiplier to your occupied_tile_fraction).
- Clamped occupied_tile_size at 0.1 to 0.9 for sanity's sake.
- Added a monster-only on_dodge() effect which grants stacking penalties to …
=> A fun combat balance pass

data/json/mapgen/nested/mansion_nested.json, src/item.cpp, src/monster.h, src/overmap_ui.cpp
Guard against potential segfault in aim code
A player on the August 5 build was experiencing a segfault when an NPC attempted to aim at a kreck.
Add some defensive coding to the aim code. I can't reproduce the issue, so it may have been fixed by backports. Still, it's always good to keep on top of this stuff.
=> Guard against potential segfault in aim code

data/json/npcs/refugee_center/surface_staff/NPC_free_merchant_teamster.json
Fix teamster response
The teamster in the refugee center was calling an accidentally backported dialogue snippet that we don't use.
Remove
=> Fix teamster response

src/consumption.cpp
Bloodfeeder enjoyment of blood gave a static +15 morale, and was easy to get +60 and even overflow the value.
Stops giving bats ability to get max enjoyment for eating or even overflowing into -60 morale.
Add fun_max of +25 to hemovore_fun flags.
Changing the position of the consumption of the enjoyment malus of eating the same thing too much, but this would cause other issues and doesn't even fix the problem.
Max value of +25 seemed fair.
Game compiles on linux, game opens and creates a character successfully, giving the bloodfeeder mutation and consuming blood only allows you to get to +25 morale and won't exceed that.
Saw the issue of this here:
https://github.com/Cataclysm-TLG/Cataclysm-TLG/issues/606
And thought I'd give it a try to fix.
=> Give bloodfeeder tag max enjoyment

src/activity_handlers.cpp, src/character.cpp, src/character.h, src/condition.cpp, src/dialogue.h, src/iuse.cpp, src/magic_spell_effect.cpp, src/map.cpp, src/map.h, src/math_parser_diag.cpp, src/npctalk.cpp, src/talker.h, src/talker_character.cpp, src/talker_character.h
Fix some minor code issues
#1123 has been identified as the PR that broke teleportation (I think by breaking location variables) but I still can't understand how. While investigating, I found a few minor errors here and there. Fixing these does not solve the problem, but they still need fixing.
=> Fix some minor code issues

src/condition.cpp, src/npctalk.cpp, src/teleport.cpp
Fix EOC teleportation
Backports broke EOC teleportation, which caused all kinds of problems, in the base game and especially with mods.
Make the value passed to teleport.cpp from npctalk.cpp non-optional. Improve the messaging somewhat.
Storing variables works. Teleporting to variables (as with MoM's loci teleport) works. It's possible the Hub 01 mercs will continue to misbehave, but I sort of doubt it.
=> Fix EOC teleportation

src/overmapbuffer.cpp, src/sdltiles.cpp
Stop drawing fake size 20 hordes everywhere.
The map screen was showing size 10 to 20 hordes all over the place, which was incorrectly displaying zombie masters and stuff on the screen. This was leading people to erroneously believe that those enemies were actually in those places.
What was really happening was that unspawned mosntergroups were all size 10 and the code was then doubling their size to "ensure their visibility". This logic might (though I doubt it) have made sense a long time ago before obscured map vision, but it certainly doesn't now. It was misleading. What appeared to be a size 20 horde could easily turn out to be like 3 monsters.
Remove the fallback display for unspawned hordes. Cap displayed horde size at 10. Now if you see a horde on your map, you know for sure it …
=> Stop drawing fake size 20 hordes everywhere.

data/json/monsterdrops/zombie_technician.json, src/character.cpp, src/game.cpp, src/handle_liquid.cpp, src/map.cpp, src/mattack_actors.cpp, src/melee.cpp, src/monattack.cpp, src/monster.cpp, src/npctalk.cpp, src/ranged.cpp, src/teleport.cpp
Fix climbing
Some iffy logic broke the ability to climb by using opposite walls/furniture/etc.
Change the logic so that it checks for a downspout or something and bails out if it won't hold you up. This still isn't perfect as if you're in a spot where you should be able to climb but there happens to be a downspout that won't hold you up there, you have to break it or move to climb, but that's a more annoying thing to fix and not nearly as big of a deal.
=> Fix climbing

data/raw/keybindings.json, src/game.cpp
Remove pointless/old/debug keybinds
Several debug features, like the scent map and creature visibility view, had options for keybinds. These are debugging tools, and putting them in the keybind menu makes players think they're meant to be using them for normal gameplay. Since I am the only developer and I do not need them as keybinds, there is no reason for them to be there.
Remove the keybinds for all debug features. You can still access these by opening the debug menu and hitting the button.
=> Remove pointless/old/debug keybinds

data/json/body_parts.json, data/json/effects.json, data/json/enchantments.json, data/json/items/armor/integrated.json, data/json/mutations/mutation_limbs.json, data/json/mutations/mutation_techs.json, data/json/mutations/mutations.json
Mutant QoL updates
Stuff I've been meaning to do based on how IRL animals work and also some gameplay concerns.
- Ursines lose mesopic, bovoids gain it
- Ursines gain Nictitating Membrane, allowing them to see underwater.
- All carnivores that don't get EATPOISON (aranean, reptilian, feline, beast) instead get EATPOISON_WEAK which allows them to eat 25% more mutant meat/day without getting sick. This should make it a bit easier to keep those mutants alive, especially early game.
- Lupines are no longer carnivores. They get the CARNIVORE_FAKE mutation like Ursine which still lets them get all the cool predator mutations, but they can eat anything.
- Ursine's Broad Paws mutation grants a bitch slap from hell if you have mutated or bionic claws of any kind and make an unarmed attack. This …
=> Mutant QoL updates

src/character.cpp, src/character.h, src/character_body.cpp, src/character_morale.cpp
Add some lifestyle penalties
There are too many lifestyle bonuses and not enough penalties.
- If morale hits -25 in a day, you get a lifestyle penalty.
- If morale hits -50 in a day, you get a bigger lifestyle penalty.
- If you are sleep deprived, you get lifestyle penalties that scale with how bad it is.
- If you eat mutant meat, you have a chance to get up to 3 lifestyle hits, depending on how much toxin you have relative to what your own personal allowance is. This allowance is adjusted by mutations and stuff, so it's less of a problem for ie carnivore mutants.
These are fairly minor and shouldn't present a problem for most characters given how many bonuses to lifestyle are available. The intent is mostly to make it less of a sure thing that you get to thriving without conscious …
=> Add some lifestyle penalties

src/cata_tiles.h, src/character_body.cpp, src/item.h, src/item_contents.cpp
Partially revert mutant meat RDA penalty
Something about #1259 broke the ability to get vitamins at all. Let's revert it until we can figure that out.
Revert that bit of the code in character_body
For some reason, vitamins seem to be giving about double what they say they ought to give. I think that's a pre-existing issue. Either way this fix is better than nothing.
=> Partially revert mutant meat RDA penalty

src/character_body.cpp
Re-add mutant meat lifestyle malus
The mutant meat lifestyle malus in #1259 broke somehow, I think it was refreshing the vitamins improperly or something. Anyway it works now.
Eating any mutant meat at all creates a small chance that you will be penalized. The chance and the penalty both go up as you eat more mutant meat, relative to the amount your body is able to withstand. This should not really be an issue for mutants who are supposed to be eating the stuff, but it still isn't ideal for them and they should be preferentially seeking out good meat.
=> Re-add mutant meat lifestyle malus

src/monster.cpp
Bleeds require damage
Due to some backports, it was possible to inflict bleeds on enemies with 0 damage attacks. These ended instantly.
You need to do at least 1 damage. Add a similar check in the make_bleed() code to be sure that bleed_rate isn't screwing it up either.
=> Bleeds require damage

src/map.cpp, src/monattack.cpp
Add a null guard to vehicles and remove debug msg
- Attempts to patch a persistent vehicle-related segfault by adding a null guard to has_vehicle_floor()
- Gets rid of a leftover debug message.
=> Add a null guard to vehicles and remove debug msg

data/json/mapgen_palettes/steel_mill_slag_palette.json
Finally stop books spawning on steel mill rails
Books were appearing on steel mill rails. This was due to an error in the slagged out steel mill's mapgen palette.
H -> S
=> Finally stop books spawning on steel mill rails

src/map.cpp
Backport 79722 - Added ground protection from bashing
The changes to bashing caused a reversion in fence-smashing, once again opening holes to the level below.
The backport adds a new roof fix.
=> Backport 79722 - Added ground protection from bashing

data/json/effects_on_condition/npc_eocs/godco_npc_eocs.json, src/condition.cpp, src/effect_on_condition.cpp, src/npctalk.cpp
Add defensive coding to EoCs, update Theresa's conditions
Backports messed up some stuff with EoCs. A lot of it got fixed, but not all.
- Revert #1285 (false alarm!)
- Modernize Theresa's EoC.
- Add some defensive coding to several places in the EoC chain of functions. These should prevent bad data from being run as EoCs (and the associated crashes) and hopefully tell us more about what is causing them.
Seems OK.
=> Add defensive coding to EoCs, update Theresa's conditions

data/json/effects_on_condition/scenario_specific_eocs.json, data/json/mutations/mutation_gradual.json
Fix mansion eoc, make gradual mutation player only
#1287 introduced an error to the mansion escape start. There was also an ongoing issue where NPCs could spawn with gradual mutation, which would run the eoc on the player due to the eoc selector.
- Revert the change to the eoc and make gradual mutation player-only. Mutant NPCs ought to be very rare and not in the general pool for the most part.
=> Fix mansion eoc, make gradual mutation player only

data/json/effects.json, data/json/mutations/mutations.json, src/character.cpp
Dogs don't sweat
- Bears were accidentally digitigrade because I didn't know about bears.
- Animals with fur and scales were sweating. Humans have sweat glands because we gave up our fur for them.
- Sweat in general was a bit nuts.
- The amount that heat was dehydrating you was always estimating near the maximum for a character exercising in the heat, and not actually checking your activity level or anything. This was happening regardless of how much you were sweating.
- Bears and bulls were really slow. That's not how those animals work!
- All sweat effects are reduced by ~23% for all characters. Sweat IRL doesn't get you instantly drenched, it just makes you kind of damp most of the time. Note that if you are wearing non-breathable clothes, you will still eventually get up to drenched …
=> Dogs don't sweat

data/json/npcs/godco/members/NPC_Julian_Ray.json
Backport 82176 - Update NECC to use faction relationship setting
NECC was saying you could sleep in their base but wouldn't actually let you do so.
=> Backport 82176 - Update NECC to use faction relationship setting

src/item.cpp
Revolvers drop casings on reload
Revolvers and some other guns were sticking the spent casings into random pockets in your inventory whenever you reloaded them. This is not how all other guns handle casings. While some people might want to keep casings, most don't, and anyway this wasn't assessing a movecost for pocketing the items.
Items with RELOAD_EJECT now dump all their spent casings on the floor when you reload them. If you are in the minority who wishes to keep them, you can simply pick them up or enable autopickup.
=> Revolvers drop casings on reload

data/json/dreams.json
Dietary dream hints
Mutants have dreams. These are partly for flavor but partly to indicate how far along you are. Some of these dreams were old and silly, and a lot of people aren't aware of dietary options that certain lines have. Dreams seem like a good place to mention those.
Add some hints to the level 4 dreams for several mutation lines about foods they might not know they like now.
=> Dietary dream hints

data/json/items/armor/ammo_pouch.json
Fix a typo in one of the quiver descriptions.
typo
lomg->long
=> Fix a typo in one of the quiver descriptions.

src/creature.cpp
Fix USE_TILES option in tiles build
Some code got mangled during a backport and broke the option to not use tiles in tiles mode.
Fix.
=> Fix USE_TILES option in tiles build

data/json/mutations/mutations.json
Remove fast healer from Reptilian
Reptilian still had fast healer
remove
=> Remove fast healer from Reptilian

data/json/monsters/fungus_zombie.json
Rename some fungal zombies
Fungal zeds suffered from having some really whimsical names that made it difficult to understand what you were fighting.
Give them regular names.
=> Rename some fungal zombies

src/construction.cpp, src/effect_on_condition.cpp, src/handle_action.cpp
Backport some NPC fixes
80301 - delay faction npc anger until you confirm construction on their turf
82332 - don't try to assign scenario EoCs to NPCs (should prevent some crashes)
=> Backport some NPC fixes

data/json/items/vehicle/tables.json, data/json/obsoletion_and_migration/migration_items.json, data/json/obsoletion_and_migration/migration_terrain.json, data/json/recipes/recipe_others.json, data/json/vehicleparts/vehicle_parts.json
Remove workbench with recharger
The workbench with recharger was a very old and very badly designed item that never quite worked the way it was meant to. It was also never properly updated to use the appliance system, and there's really just no reason it should exist given the functionality of modern chargers.
remove
=> Remove workbench with recharger

data/json/items/armor/jewelry.json, data/json/npcs/godco/godco_missions.json
NECC fixes
- Corrie's quest was asking for "a solar panel" in the text, but you actually need 4 panels or an array.
- Relics weren't wearable.
- Corrie now specifies what she means, and her advice now tells you to look on roofs rather than for a solar car, as those aren't very common.
- Relics are now wearable.
=> NECC fixes

data/json/itemgroups/Drugs_Tobacco_Alcohol/drugs.json, data/json/items/tool/med.json, data/json/recipes/nested.json, data/json/recipes/other/medical.json, data/json/requirements/materials.json
Adjust first aid amounts, add recipe
- Too many band-aids, tampons, and alcohol wipes per box.
- There was no way to make an improvised bandage out of cloth or tissue and tape.
- Bandage recipe was wrong.
- While we're here, remember to fix the fletching requirements.
- Adhesive bandages and alcohol wipes now come in boxes of up to 10.
- Tampons and pads are now up to 18 instead of up to 24. Bigger boxes exist irl, but 18 is a common size, and keeps our numbers that much saner.
- Renames adhesive gauze bandage to adhesive gauze patch, hopefully making it clear it's a larger bandage.
- Adds a new item, makeshift gauze patch. This is just duct tape and toilet paper or some such. Surprisingly effective and quick to apply, but nowhere near as good as the real thing.
- Adjusts bandage recipe. …
=> Adjust first aid amounts, add recipe

data/json/items/tool/firefighting.json, src/activity_actor.cpp
Fix pulp bug, adjust math
- If the player was holding a 0 damage item while pulping corpses, it was possible to segfault.
- The math for multi-damage weapons and larger creatures needed tweaking.
- Reduce the time discount for huge creatures. They were too easy to pulp.
- Increase the bonus for survival skill by 20%
- Make cut and stab weapons a bit less bad at pulping.
- Fix some integer division issues, and fix an issue with multiple damage types not getting their ratios properly checked.
Seems good. In rare cases it's possible to spend way too long pulping a corpse and to get super weary super fast. I need to devise a fix for that which doesn't break NPC behavior.
=> Fix pulp bug, adjust math

src/faction.cpp, src/faction_camp.cpp
Faction board shows vitamins
The faction camp board has a lot of very old, outdated, confusing, and badly written information on it. Like most features involving NPCs, it generally does a horrible job explaining itself.
- The faction camp board no longer has a bunch of math and nonsense on it in the "distribute food" job. Now it simply tells you how it works, how many kcal you have in storage, and what your faction's vitamin/toxin situation is. This information was already available on the faction menu, but it wasn't displaying properly due to some bad math.
For some reason, I can't currently distribute multivitamins despite their being an explicit option to do so. I'll have to figure that out, but this works fine for now.
=> Faction board shows vitamins

src/iuse.cpp
Release grabs before capturing monsters
If you had a grappled monster and tried to put it in an animal carrier or pet carrier, it would segfault.
When putting a monster in a carrier, check if the character is grappling, check if the grapple target is the monster in question, and release it if so, then put it in the carrier.
Grabbed a little dog and shoved it in a pet carrier. Success.
=> Release grabs before capturing animals

data/json/items/tool/musical_instruments.json
Deletion of the golden violin item. Edited the krar from gold to wood.
Deletion of the golden violin item, changes to the krar to account for it being wood instead of gold. 
Cleaning up some legacy musical instruments and updating the krar (harp)
Deletion of the golden violin item, changes to the krar to account for it being wood instead of gold. I also changed the weight of the krar to be in line with harps, roughly 15 lbs on the low end.
None.
Ran fine with no errors.
=> Remove golden violin, change krar from gold to wood.json

doc/JSON_INFO.md, doc/OVERMAP.md, src/advanced_inv.cpp, src/character.cpp, src/character.h, src/character_attire.cpp, src/character_attire.h, src/item.cpp, src/item.h, src/item_contents.cpp, src/item_contents.h, src/npc.cpp, src/overmap_ui.cpp, src/vehicle.cpp
aw mom, just one more backport before bed?
These are mostly bugfixes and infrastructure. I need that rotor thrust update to fix helicopters, and the NPC thing should be an immediate help.
79305 - refactor pocket code
79314 - prevent NPCs from walking off cliffs
79309 - overmap documentation to include missing field
79316 - misc fixes for unloading via AIM
79325 - unhardcode overmap filter popup text
79328 - add part bonus for rotor thrust
=> aw mom, just one more backport before bed?

src/monster.cpp, src/player_hardcoded_effects.cpp
Improve hardcoded effect text
The text for anemia and mutant toxin were a bit weird and in some cases misleading.
Improve the text and in some cases make the effects work a bit better.
=> Improve hardcoded effect text

data/json/bionics.json
This change adds bionic power costs to many of the "passive" bionics that provide bonuses via electronic means. It also allows you to toggle them on/off. 
Bionics that are described as functioning actively should not be able to function without power. This change adds a toggle & power drain to 
Wired Reflexes
Cerebral Booster
Muscle Augmentation
Recoil Compensators
Synaptic Accelerator
It also adds a power cost to enhanced hearing while active. 
I've added a small placeholder power drain to the listed CBMs. Made them sleep friendly. Given them on/off toggles.
None
Works as intended & without error.
=> Add Bionic Power Cost to "Passive" Enhancement CBMS

src/activity_actor.cpp
Backport DDA 79556 - fix insert segfault
Inserting items with v was causing a segfault due to DDA 79518.
Add a null guard.
Can insert, no crash.
=> Backport DDA 79556 - fix insert segfault

data/json/npcs/common_chat/TALK_FRIEND_CONVERSATION.json
Remove psychopath chat penalty
Psychopaths were being given a morale penalty for chitchatting with NPC pals. That's not appropriate. They don't hate you, they just don't feel the way you feel.
Remove the morale penalty. They still get no bonus.
=> Remove psychopath chat penalty

data/json/recipes/recipe_ammo.json
Fix wooden bodkin arrow recipe resulting amount
Make wooden bodkin arrows recipe produce only 1 arrow
Removed the amount of charges on its recipe result json
None
Before:
After:
None
=> fix crafting amount of bodkin arrows

src/game.cpp, src/game.h, src/map.cpp, src/monmove.cpp, src/monster.h
Backport bugfixes
Some infrastructural bugfixes.
79053 - don't place null monsters or on null positions
79081 - reworked spawn_monsters_submap to handle non bub maps
=> Backport bugfixes

src/character_morale.cpp, src/npc.cpp
Fix murder and nomad morale
The check for assigning a morale penalty when murdering an innocent was all sorts of stupid, primarily because it was tied up with the check for whether the player would be blamed (by the target) for attacking them. There were checks in place to try to make sure this didn't cause issues, but they famously broke all the time and were just really annoying to deal with, and what's worse is that all of this was only being applied to the player character.
As for the nomad traits (do we really need 3 of them?), these had such ridiculously short timers that they essentially made the game unplayable, with NOMAD3 capping its penalty at just 2 hours.
- Move the murder check out of on_hit() and explicitly define it in npc::die().
- Simplify some of the trait interactions. …
=> Fix murder and nomad morale

data/json/mapgen/prison/prison_island.json, data/json/monsters/feral_humans.json
Remove zombie master from prison island start
One of the island prison starts had a guaranteed zombie master in the warden's office. That was cute, but while you spent hours trying to solve the escape room puzzle, he'd be upgrading every single zombie that walked by his window, which generally wound up making the scenario unwinnable.
Replace him with a unique feral that has a rifle.
He shot me through the window.
=> Remove zombie master from prison island start

data/json/furniture_and_terrain/furniture-storage.json, src/handle_action.cpp
Stronger furniture, better smashing
- Constant "keep smashing" prompt was annoying, no way to disable.
- Some furniture (mostly safes) was too easy to bash.
- Raise bash strength of safes to 50, adjust some other random things most people will never notice.
- To get the "keep smashing" prompt, smash the same spot 3 times in a row. If you say no, you won't see it again until you smash someplace else, pause, or move.
- Probably some random other actions ought to reset the counter too.
=> Stronger furniture, better smashing

src/faction_camp.cpp, src/handle_action.cpp
Fix backport of 76105
Either due to a regression or an issue with the backport script (seems likelier since I tried to run it again with the same result), the check for whether the player was the one distributing food was getting skipped, so NPC factions distributing food, like when you give food to the refugee center, were causing popup messages that shouldn't have been there.
Manually backport the solution in DDA 76015
=> Fix backport of 76105

data/json/items/armor/cloaks.json, data/json/items/armor/suits_clothes.json
Adjust denim overalls and cloak thickness
The denim overalls and cloak were a bit too thick, providing more protection than intended.
Make them less thick.
=> Adjust denim overalls and cloak thickness

src/character.cpp, src/debug_menu.cpp, src/point.cpp
Build "Fix compile errors"
Some compilation errors were thrown when compiling with `make CCACHE=1 TILES=1 SOUND=1 LOCALIZE=0 BACKTRACE=0 ASTYLE=0 LINTJSON=0 TESTS=0 RUNTESTS=0 CLANG=1 RELEASE=0`.
The errors were:
```
src/character.cpp:13832:20: error: left operand of comma operator has no effect [-Werror,-Wunused-value]                                                                                                                                                                       
13832 |                 _( "You roll on the ground, trying to smother the fire!" ),                                                                                                                                                                                           
| …
```
=> Fix some compile errors

data/json/obsoletion_and_migration/obsolete_overmap_special.json, data/json/overmap/overmap_special/specials.json
Fix bandit farm obsoletion
#1405 removed the bandit farm, but I forgot to remove one of the overmap definitions, so the obsoletion didn't work.
Remove it!
No more warnings or crashes.
=> Fix bandit farm obsoletion

data/json/effects.json, src/consumption.cpp
Nasty food can make you hurl
More food interactivity! More incentive not to eat horrible garbage!
- Characters who are squeamish will simply refuse to drink blood unless they're hemovores or carnivores, or they're starving.
- Eating really gross food ( total fun value <= -5 after all modifiers for traits, bionics etc are applied) has a chance to make you nauseated. This chance scales with how gross the food is. The nausea chance goes up by 5% for picky eaters, plus a bunch of other factors like squeamish + eating raw meat while not a carnivore, eating human flesh while not a cannibal, etc. In most cases these chances are mitigated by increasing the food's enjoyability value through cooking or other means.
- Improved some messaging related to food.
Remember that nauseated does not mean …
=> Nasty food can make you hurl

data/json/items/armor/torso_armor.json
Fix chainmail vest adjustment
- The chainmail vest wasn't properly adjusting to OUTER when activated. This is because it didn't explicitly have the NORMAL flag set.  Now it does.
=> Fix chainmail vest adjustment

data/json/furniture_and_terrain/appliances.json, data/json/obsoletion_and_migration/migration_items.json, data/json/recipes/other/power_supplies.json, data/json/vehicleparts/vehicle_parts.json
Update solars and turbines
- For legacy reasons, it was possible to build functional wind turbines and water wheels on cars and boats. I should not have to explain why this is preposterous.
- "Reinforced glass" is not what DDA thinks it is, and would be of no benefit to solar panels, which are already made of stronger stuff.
- Remove the vehicle versions of wind turbine, large wind turbine, water wheel, and large water wheel. These items are only available as appliances.
- Update the descriptions, recipes, and stats for reinforced solar panels. These items are now described and statted as being bound up and secured with wire, providing a modicum of protection but impeding power generation.
- Updated the bash results for all kinds of solar panels.
- Built all the stuff and it worked, no …
=> Update solars and turbines

data/json/items/comestibles/carnivore.json, data/json/items/comestibles/dairy.json, src/iuse.cpp
You can't just eat lard
- Lard, butter, tallow, and cooking oil should not be edible in large quantities without getting sick.
- Add the BLECH use_action to lard, tallow, and butter.
- Adjust the duration of BLECH nausea (randomizing it a bit) and adjust the messaging to be more generally applicable.
- BLECH and other food-related iuse actions should be moved to consumption.
- Ate tallow, kept it down, tried again and got sick.
=> You can't just eat lard

data/json/overmap/overmap_special/specials.json
Missile silo is globally unique
The missile silo, a story setpiece with huge amounts of loot, was set to overmap_unique, so they were spawning all over the place.
Globally_unique.
=> Missile silo is globally unique

src/monster.cpp
Fix contagion
- There was a longstanding bug inherited from DDA in how cold/flu contagion worked. Instead of checking every X seconds, it checked every second. Given that the base chance to get sick is 33%, you were rolling those dice every single second you were in melee with a sick feral. That's a really bad bug, and meant that you'd basically always get sick if you encountered one.
- Only the player was able to get sick.
- It was only possible to get sick in melee range.
The check now rolls one_in( 400 ) for cold and 300 for flu each second. When it procs, it checks clear_path to all characters within 4 tiles (cold) and 5 tiles (flu). That's every 6.66 and 5 minutes respectively, though note that's an average and not an absolute.
There needs to be a version of clear_path that ignores …
=> Fix contagion

data/json/vehicleparts/cargo.json
Box install and removal require same skill
Installing a box on a vehicle took only one mechanics, but for some reason, removing it took 2.
- Make it take 1 for both. Make bike racks (which had the same problem) take 2 for both, as that's a more complex part.
=> Box install and removal require same skill

data/json/npcs/tacoma_ranch/NPC_ranch_foreman.json
Tacoma blanket mission accepts quilts
There's a Tacoma mission where you need 25 blankets, but there are a bunch of blanket items and some weren't working.
Add quilt and patchwork quilt to the accepted item list.
=> Tacoma blanket mission accepts quilts

src/avatar.cpp, src/character.cpp
Remove time penalty for reading ebooks in dim light
Ebooks were readable in the dark, but it was still applying a penalty as if you were having trouble seeing.
Remove the penalty for backlit devices.
=> Remove time penalty for reading ebooks in dim light

src/avatar.cpp, src/editmap.cpp, src/game.cpp, src/map.cpp, src/map_extras.cpp, src/mapgen.cpp, src/monster.cpp, src/vehicle.cpp, src/vehicle.h, src/vehicle_move.cpp, src/vehicle_use.cpp, tests/item_spawn_test.cpp
Backport 79208 - typified sm_pos in vehicle
This PR was left out and needed to be done before #1359 .
Reverted two of the backports in there and then applied this. It had some trouble in map.cpp as a rogue ++iter was appearing in // Destroy bugged non-part vehicles due to having preponed the map cache stuff.
=> Backport 79208 - typified sm_pos in vehicle

src/npctalk.cpp
Add npc door behaviour overrides: don't walk through closed doors and leave doors open
To ease micromanaging npcs behaviour. Currently, these two options are only toggleable through chatting directly with npcs. If you have multiple npcs following you, this change will make it easier to control them.
Added override options on the Chat with NPC menu -> (o) Tell everyone on your team to temporarily...
Those two options are bound to the `w` and `a` keys.
The `c` and `d` keys were already occupied on this menu, so I figured it is better to not change them, to avoid player misinput from muscle memory.
Got a follower npc, set their miscellaneous behaviour to default, used Chat with npc menu to override them. Video below.
I would like feedback on whether the `w` and `a` keys are good for this. …
=> Add npc door behaviour overrides

data/json/items/tool_armor.json
Add storage to AR glasses
Basic AR glasses didn't have storage, so they couldn't store their photos.
=> Add storage to AR glasses

data/json/overmap/overmap_terrain/overmap_terrain_transportation.json
Disable (for now) riot damage in subways
We're not using riot damage for now, so this shouldn't be enabled.
=> Disable (for now) riot damage in subways

data/json/monsters/fungus_zombie.json, data/json/npcs/island_prison/prisoners.json
Clarify prison quest
Despite the fact that the island prison quest clearly tells you to go to the chief's office, every player who has ever done the island prison start has indelibly internalized the belief that they're being told to go the warden's office. These are different places!
The quest was also a bit unclear because for no reason at all, the quest giver was being unhelpfully cagey about what item he actually wanted. He wants a military ID card. There's no reason to hide that information from the player.
- Update the title of the mission to clarify that the player is looking for a military ID card.
- Update the mission text to be more clear that the player is looking for the chief corrections officer and not the warden.
=> Clarify prison quest

data/json/items/armor/coats.json, data/json/items/armor/gloves.json, data/json/items/armor/legs_clothes.json, data/json/items/armor/torso_clothes.json
Rainproof audit
A bunch of items that should have been rainproof were not. A bunch of items were water-friendly that should not be.
Fix flags.
=> Rainproof audit

data/json/ammo_effects.json, data/json/items/comestibles/egg.json, src/character.cpp, src/current_map.cpp, src/current_map.h, src/debug_menu.cpp, src/explosion.cpp, src/faction_camp.cpp, src/game.cpp, src/game.h, src/map.cpp, src/map_extras.cpp, src/mapgen.cpp, src/mission_companion.cpp, src/mission_start.cpp, src/npctalk.cpp, src/start_location.cpp
Map backports
80548 - swap map returned by get_map()
80773 - translate coords correctly
80782 - added swap safeguard to temp map access
=> Map backports

data/json/furniture_and_terrain/terrain-walls.json, data/raw/keybindings.json, src/iuse_actor.cpp, src/savegame_json.cpp, src/veh_appliance.cpp, src/veh_appliance.h, src/vehicle.h, src/vehicle_display.cpp
Backport 78888 and 78515 - wiring stuff
Clarify the text for plugging in tools and give wall wiring displays a toggle.
=> Backport 78888 and 78515 - wiring stuff

data/json/items/armor/legs_clothes.json, data/json/vehicleparts/modular_tools.json
Typo fixes to utility kilt and mounted workshop
Typo fixes to utility kilt and mounted workshop
Typo fixes to utility kilt and mounted workshop
Fixed the typos
None
Runs fine, typos are gone.
=> Kilt & workshop typos

data/mods/innawood/recipes/recipe_vehicle.json
Update yoke_harness recipe to replace tanned_hide with sheet_leather.
Tanned hide has been replaced by leather sheets after the consolidation of sheet_leather and tanned_hide in #1469.
Replace tanned_hide with sheet_leather.
None
Loads without errors, and recipe works.
=> Innawood - Update yoke_harness recipe

src/savegame.cpp
It complains about narrowing here, but mac needs uint64_t for deserializing - use a cast to silence it.
Fix android32 build
81199
```
changeset:   98a88b8e1f09066648c11353a710db3776885327
user:        ehughsbaird <44244083+ehughsbaird@users.noreply.github.com>
date:        Sat, 07 Jun 2025 08:33:48 -0700
summary:     Fix emscripten build
```
=> Fix android32 build

src/map.cpp, src/vehicle.cpp
Fix a bad get_map()
Players were infrequently experiencing segfaults. While looking into the crash reports, I discovered the issue was one reported on DDA's github. Mapifying some functions meant that calling get_map() inside of them was getting the player's map instead of the one they were trying to work on.
A separate issue appeared to be caused by vehicle bashing. In some unknown circumstance I cannot reproduce, items stored within a vehicle tile were somehow causing a segfault when that tile was destroyed and its contents were to be placed on the ground. It's possible the items were being destroyed or they hadn't loaded in yet or some other thing (in this instance it was caused by riot damage, which was briefly enabled).
Issue 1: get_map() -> *this
Issue 2:  Since I don't know what's …
=> Fix a bad get_map()

src/npcmove.cpp
Improve NPC pulping behavior
- NPCs were using their combat range as their pulping range. This is unintuitive, as combat is not pulping.
- NPCs were complaining about wanting to go pulp corpses even if they had been told to keep quiet.
Pulp range is now 6, which was the previous maximum. It will drops to 4 or 2 if you have the NPC set to follow you closely. This may allow them to step slightly more than 2 or 4 steps away from you, but it's assumed you're OK with that if you have pulping left on.
NPCs will not mention wanting to pulp corpses if you have told them to be quiet.
Seems to work as intended.
=> Improve NPC pulping behavior

data/mods/Megafauna/items/animal_products.json
Fix megafauna eggs
Titanis walleri and great auk eggs were throwing errors.
Error no more.
=> Fix megafauna eggs

src/creature_tracker.cpp, src/mapgen.cpp
Silence two common error messages
Silence two common error messages
Silence two common error messages
Silence one or zero common error messages
Two common error messages silenced
The "furniture exists at x" thing is a constant bane of nested mapgen, often popping up even when the nested map is flagged to ignore it. It's also annoying when you knock down a building or something. Like yeah OK the terrain changed, who cares.
"There's already a monster at pos" was similarly unhelpful. This mostly happens when monsters try to use invalid movement because they're packed in too tightly or fall on top of each other. It almost always immediately resolves itself and the player never really needs to know about this.
=> Silence two common error messages

data/json/mapgen/nested/road_vehicles_nested.json
Backport 80642 - put vehicles inbound
Vehicles were spawning with weird errors sometimes, like just a corner floating in space, but vision blocked as though the whole vehicle was there.
=> Backport 80642 - put vehicles inbound

data/json/items/gun/shot.json, data/json/items/gunmod/rail.json, data/json/items/gunmod/underbarrel.json
The 870 breacher was missing a loading port so it couldn't have it's speedloader chute attached.
This also fixes the error on offset grips that referenced removed weapons.
Lastly removes an integrated underbarrel shotgun for a weapon thats no longer in game. 
The 870 breacher was missing a loading port so it couldn't have it's speedloader chute attached.
This also fixes the error on offset grips that referenced removed weapons.
Lastly removes an integrated underbarrel shotgun for a weapon thats no longer in game. 
Added a loading port location
deleted referenced to removed weapons from offset grips
Lastly removes an integrated underbarrel shotgun for a weapon thats no longer in game. 
Cursory online check to see whether a speedloader could be attached to this gun, also noticed that there …
=> Gun tweaks (870 breacher & offset grip)

data/json/items/gun/22.json
Remove bayonet lug from marlin
Someone noticed the marlin had a bayonet lug. This must have been an error because this is a varmint rifle, not a weapon of war.
=> Remove bayonet lug from marlin

data/json/mapgen/basement/basement_lab_stairs.json, data/json/overmap/multitile_city_buildings.json, data/json/overmap/overmap_connections.json, data/json/overmap/overmap_special/specials.json, data/json/overmap/special_locations.json, data/json/regional_map_settings.json, data/mods/classic_zombies/alberta_regional_map_settings.json, src/activity_actor.cpp, src/activity_handlers.cpp, src/activity_item_handling.cpp, src/craft_command.cpp, src/debug_menu.cpp, src/game.cpp, src/handle_action.cpp, src/map.cpp, src/map.h, src/mission_start.cpp, src/monattack.cpp, src/monexamine.cpp, src/monmove.cpp, src/npcmove.cpp, src/npctrade_utils.cpp, src/pathfinding.cpp, src/pathfinding.h, tests/map_path_test.cpp, tests/vehicle_fake_part_test.cpp
April Backports
81009 - fix refugee center lab mission not finding target
80581 - allow multiple pathfind targets
80582 - set faction owner of in-progress crafts
=> April Backports

src/mapgen.cpp
Backport 80773 again
Due to a reversion or ommission, 80773 wasn't properly backported before, resulting in NPCs spawning outside of their faction bases.
works
=> Backport 80773 again

data/mods/Megafauna/monstergroups/wilderness.json, data/mods/Megafauna/recipes/recipe_others.json
Fix mammoth shelter kits looking for an obsolete tanned hide item.
Fix bullfrog entries.
Both were throwing errors, but bullfrog entries were preventing world loading.
Loads and no errors :)
I have no idea if I did the bullfrog start and end values correctly. Let me know what they need to be adjusted to if they are incorrect.
I will be doing a backport of #75551 Clean up Megafauna wilderness spawns. Soon.
=> Megafauna - Fix some errors

src/item.cpp
Mapgen corpse birthdays
Because of the fact that we spawn items at start_of_cataclysm, which is 20 days before fall_of_civilization (game start), corpses placed by place_items or similar methods in mapgen were already 20 days old. This meant that they would immediately revive if possible and would usually immediately evolve, sometimes more than once! The whole purpose of splitting the two dates up was to give some time for comestibles to decay while keeping zombie evo pinned to the presumed date of game start.
- Add a section to randomize_rot() which randomizes the birthdays of corpses, making them between 0 and 3 days old at game start.
- Adjust the minimum random decay timer on food, allowing it to be just 2 days old at game start. Its maximum of 24 days remains unchanged.
I considered …
=> Mapgen corpse birthdays

data/json/professions.json, data/json/snippets/snippets.json
Changed which bionic professions get MK1 or MK2 batteries and what powers them.
Edit to Dog Tags so that they read Jewish instead of Jew.
Changed which bionic professions get MK1 or MK2 batteries and what powers them.
Edit to Dog Tags so that they read Jewish instead of Jew.
Razor girl had two bionics that previously did not require power that now do. 
https://github.com/Cataclysm-TLG/Cataclysm-TLG/pull/1360
I've added power storage and a form of power generation to the razor girl.
I've also changed which professions get tier 1 or 2 batteries and what powers them.
Profession changes as follows:
High tech - government funded/ described as costing millions of dollars
Have MK2 battery
1) Razor Girl - metabolic
2) Bionic Agent - metabolic
3) Bionic Operator - metabolic
4) Bionic Sniper - …
=> Bionic Profession Update & Dog Tag Edit

src/item.cpp
This didn't need to be done, and the corpses were fine as is. If the whole evo thing gets fixed, we can un-revert this and take another look.
=> Revert "Mapgen corpse birthdays"

src/options.cpp
Backport 75447 - Use CC-Sounds as default soundpack if it's present on first launch
People didn't know how to enable their soundpack.
=> Backport 75447 - Use CC-Sounds as default soundpack if it's present on first launch

data/json/items/armor/bandolier.json, data/json/obsoletion_and_migration/migration_items.json, data/json/recipes/armor/storage.json
Stone pouch: Absolutely the fuck not
Stone pouches were one of the worst examples of backwards logic in the game, being a PALS-compatible pouch which only added 4 encumbrance to one leg and could hold 10 rocks or 80 pebbles and allowed the player to retrieve rocks in 1/5th of a second. What the _fuck_
Just to clarify, a rock is the size of a baseball and weighs 1.5 pounds. A pebble is palm-sized. That's a preposterous amount of stuff to be sticking in a PALS bag and there's no earthly reason such an arrangement should be faster than picking one of these items up out of almost any other container. These seem like items which were implemented by someone who wanted to have a huge super fast low-encumbrance bag of rocks and worked backwards from there, and that's not how we do things.
Gone. …
=> Stone pouch: Absolutely the fuck not

data/json/recipes/practice/applied_science.json, data/json/recipes/weapon/explosive.json
No acid blood for acid bombs
It was possible to make acid bombs out of acid blood, and these bombs would be good forever despite the fact that the blood is rapidly breaking down and becoming useless. There are recipes to convert acid blood into pure acid, so the player ought to be using those.
- Remove acid blood from the acid bomb recipes.
- Make the acid blood related practice recipes require some sort of chemistry textbook.
=> No acid blood for acid bombs

data/json/effects_on_condition/effects_eocs.json, data/json/effects_on_condition/item_eocs.json, data/json/itemgroups/corpses.json, data/json/professions.json, data/json/recipes/weapon/explosive.json, data/json/requirements/tailoring.json, src/character_attire.cpp, src/item.cpp
Fix several EOCs
Backport churn broke a bunch of our EOCs, including bile, acid, sunglasses, and introvert/extrovert/social/asocial. These needed immediate attention.
- Update the EOCs using the new event system so that they actually trigger.
- Update the character_removes_item event to take place AFTER the item is actually removed. Previously it was firing before, so in the case of sunglasses, we couldn't check to make sure that the character wasn't wearing any other items with the flag.
- I need to go through the seasonal mutation stuff, but IIRC that all uses recurrence so maybe we're fine.
- Sunglasses, asocial, and boomer stink all work.
=> Fix several EOCs

src/zzip.cpp, tools/save/zzip_main.cpp
Backport 83182 - fix zzip
zzip was a bit broken and couldn't manually uncompress saves.
Backport!
=> Backport 83182 - fix zzip

src/iuse.cpp, src/npctalk.cpp, src/requirements.cpp, src/vehicle.cpp
A couple of backports
80566 - fix eoc location variable
80578 - in progress crafts can't target specific location variable
80579 - silence some warnings when compiling
=> A couple of backports

src/avatar.cpp, src/avatar.h, src/avatar_action.cpp, src/character.cpp, src/character.h, src/character_inventory.cpp, src/game_inventory.cpp, src/item_location.cpp, src/iuse_actor.cpp
Fix holsters
A player submitted a bug report mentioning that they heard their sfx slow down when they drew a weapon. We soon discovered that the movecost for drawing a weapon was around negative three seconds. This led me down a very deep rabbit hole, but basically holsters and drawing/sheathing were completely broken in general.
- Get rid of avatar::wield_contents and character::wield_contents. These were totally redundant, didn't work properly, and only used when you (a)ctivated a holster. Wielding from a holster using (w)ield was fine, so we can just use the same function if the player uses the activate menu instead of wielding.
- Get rid of any mention of holsters being exempt from speed penalties.
- Make it impossible to activate holsters unless they're worn. They function as …
=> Fix holsters

src/item_location.cpp
Fix MOLLE holsters
Holsters attached to MOLLE gear weren't discounting wield costs because the code was set up to check for the holster action, which is not present in that case.
Check instead for the holster pocket type.
=> Fix MOLLE holsters

data/json/items/comestibles/bread.json
Updates johnnycakes to be made of vegetables (corn) rather than wheat in the final craft.
Johnnycakes were made of wheat in the final craft rather than vegetables. This corrects that.
Lets people with gluten allergies eat johnnycakes
Changes the vitamins & material of johnnycakes from wheat to vegetable
None
Runs fine & without error. Wheat intolerant characters can now eat johnnycakes without negative effects.
=> Updates johnnycakes
