.github/workflows/msvc-full-features.yml
.github/workflows/release.yml

Backport dda 74587 - Drop object creator builds from CI

---

.github/workflows/release.yml

Almost totally untested.
Should work (tm), maybe.

Fix release tag in release.yml

---

README.md

Add link to website and discord in readme
Difficult to find the discord (had to scan through reddit comments) and website is WIP.
Adds link to website and discord in readme
None
The discord link is valid and set to never expire and the website link is copy and pasted from the discord, it doesn't work at the moment but once the site's up I imagine it will
None

Add link to website and discord in readme

---

data/mods/innawood/recipes/armor/feet
data/mods/innawood/recipes/armor/head.json
data/mods/innawood/recipes/armor/storage.json
data/mods/innawood/recipes/armor/torso.json
data/mods/innawood/recipes/weapon/ranged.json

Category "Innawoods Mod Crafting Balance"
Adjusted the recipe requirements for certain clothing items that could realistically be crafted without the need for metal tools. Additionally, shortened the craft time of certain recipes to bring them in line with the craft times of similar unchanged items
Currently, most clothing recipes require Fabric Cutting 1, which necessitates access to metal tools. This means players must advance to at least the Bronze Age before they can craft anything beyond the most primitive coverings, such as grass skirts.
This change improves accessibility by allowing basic clothing items to be crafted without metal tools, reflecting historical and real-world methods of garment creation using stone, bone, or simple cutting techniques.
Adjusted crafting requirements …

Recipe adjustments for Innawoods stone age clothing and equipment

---

.github/macports/macports.yml
.github/workflows/matrix.yml
.github/workflows/release.yml
Makefile

Backport DDA 77818 - Fix mac CI

---

.github/workflows/matrix.yml
.github/workflows/release.yml

Build stuff part 3, thanks to #407 for the tip

Backport DDA 79297 - Pin versions in setup-sdl2 workflow step since SDL3 was released

---

src/character.cpp
src/character.h

Switch some timing stuff so that it doesn't conflict with how Android works, I guess?

Backport DDA 67090 - Fix android build

---

src/character.cpp
src/character.h

Reverts Cataclysm-TLG/Cataclysm-TLG#433
Seems to make it worse, not better.

Revert "Backport DDA 67090 - Fix android build"

---

android/app/build.gradle

More dda->tlg in android build files

yet more android fixes

---

src/mapgen.cpp

backport 74687 - Fixed monster rain + rotation havoc
Fixes needed for 3d mapgen
Compiles, runs, caves look normal.

backport 74687 - Fixed monster rain + rotation havoc

---

src/activity_handlers.cpp
src/inventory_ui.cpp
src/inventory_ui.h

Minor astyle fixes

---

src/monster.cpp
src/ranged.cpp

Fix major grappling bug, minor throwing bugs
- Grappling had a major bug where if you killed an enemy while grabbing them, the game could crash.
- Throwing was not appropriately damaging enemies when they collided with obstacles.
- The throwing sidebar wasn't giving any feedback.
- Add some proper grab cleanup code to monster::die() which ensures a grabbed monster who dies doesn't trip a segfault somewhere else.
- Change the impact() check to exempt for monsters who are actually flying, not ones who are merely airborne (lol)
- Copy the item-throwing code's sidebar stuff over to monster-throwing. This allows it to show the expected # of moves, however it shows an accuracy bar which is not correct. That's another issue.
- The accuracy bar should instead be a throwforce bar, indicating …

Fix major grappling bug, minor throwing bugs

---

data/json/obsoletion_and_migration/migration_items.json

Fix mistake in #515 
Merged before I had finished pushing. Rookie mistake!

Migration fix (doh)

---

data/json/itemgroups/Locations_MapExtras/locations_commercial.json
data/json/itemgroups/Locations_MapExtras/locations_mapextras.json
data/json/itemgroups/activities_hobbies.json
data/json/itemgroups/tools.json
data/json/itemgroups/trash_and_debris.json
data/json/itemgroups/vehicles_fuel_related.json

Friday night and you're all alone editing itemgroups? ...pathetic.
Rubber sealant spray was spawning without a container.
Fix the got damn rubber sealant spray once and for good.

Friday night and you're all alone editing itemgroups? ...pathetic.

---

data/json/obsoletion_and_migration/migration_items.json

Fix a fursuit migration
The tiger fursuit migration had the wrong ID.
tiger_suit->tiger_fursuit

Fix a fursuit migration

---

data/mods/TEST_DATA/field_type_migrations.json
data/mods/TEST_DATA/fields.json
doc/OBSOLETION_AND_MIGRATION.md
src/init.cpp
src/mapdata.h
src/savegame_json.cpp
tests/submap_load_test.cpp

Backport 74497 - Field type migration

Backport 74497 - Field type migration

---

data/json/items/book/dodge.json
data/json/items/comestibles/meat_dishes.json
data/json/items/tool/unfoldable.json
data/mods/Sky_Island/upgrade_missions.json
src/iuse.cpp

Backport DDA 74538 - Bunch of random fixes

Backport DDA 74538 - Bunch of random fixes

---

src/action.cpp
src/action.h
src/character.cpp
src/character.h
src/game.cpp
src/game.h
src/iexamine.cpp
src/iexamine.h
src/map.cpp
src/map.h
src/mapdata.cpp
src/mapdata.h
src/submap.cpp
src/submap.h
src/trap.cpp
src/trap.h
src/vehicle.h
src/vehicle_use.cpp
tests/vehicle_fake_part_test.cpp

Backport DDA 74796 - Typified action.h/cpp

Backport DDA 74796 - Typified action.h/cpp

---

src/visitable.cpp

Misclicked the merge button before I was ready!

Revert "Backport DDA 75103 & 75270 for performance"

---

data/json/furniture_and_terrain/furniture-domestic_plants.json
src/consumption.cpp

Fix farm plant bug
A wire got crossed during #634 and I messed up a plant json, causing some weird issues.
Fix that minor json error

Deadplant fix

---

src/map.cpp

Work around AIM-related save/load crashes.
In some cases, the state of the Advanced Inventory Manager appears to become invalid (perhaps due to being open on nested containers which get removed via other UIs).
This change adds a null-pointer check to let the game finish saving/loading in some of these cases without crashing, and instead only displaying some warnings.
Properly figure out the root cause of this invalid state.  I suspect that something about entering a deep nesting hierarchy (like an ammo can) in the AIM, and then reorganizing it via other commands (like multidrop), and possibly going far away from the place of those interactions, might lead to this, but I don't have a clear reproduction yet other than my savefile.
It would also be great to have the in-game warning screens …

Avoid segmentation fault from invalid uistate.json

---

data/json/flags.json
data/json/item_actions.json
data/json/items/armor/cloaks.json
doc/DEVELOPER_FAQ.md
doc/JSON_FLAGS.md
src/cata_tiles.cpp
src/cata_tiles.h
src/item_factory.cpp
src/iuse.cpp
src/iuse.h

Backport 77903 - Allow flags to be posted to walls

Backport 77903 - Allow flags to be posted to walls

---

src/avatar.cpp
src/character.cpp

Fix Bendy Limbs p2
Forgot to push some code. Ignore this!

Add code I forgot to push

---

build-scripts/get_all_mods.py

Backport 78676 - group mod interactions
Update mod script and prep for backporting 81406

Backport 78676 - group mod interactions

---

data/json/itemgroups/Locations_MapExtras/locations_commercial.json
data/json/itemgroups/Weapons_Mods_Ammo/archery_weapons.json
data/json/items/melee/bludgeons.json
data/json/items/melee/knives.json
data/json/items/tool/landscaping.json
data/json/monsterdrops/zombie_default.json
data/json/monsters/fungus.json
data/json/npcs/NC_NONE.json

More various fixes
Shut a couple of error messages up
json fixes

More various fixes

---

src/math_parser_impl.h

Update math_parser_impl.h to include missing dialogue methods
fixes #967 
Following what the crash log in 967 suggests, I updated thingie::eval() to have a better fallback which should avoid crashes even if it catches something it isn't designed for.
Loaded the save, crafted stuff, ignored the hallucinations, no problems.
I think this might have been a mod-specific bug. I can only assume MoM was trying to run an EOC that was not prepared to deal with hallucinations. It's possible I was wrong about this fix as I didn't install MoM, but if that's the case then it's MoM's problem to fix and not mine.

Update math_parser_impl.h to include missing dialogue methods

---

src/catacharset.cpp

Possibly maybe correct a bug in the Steam Linux build
Steam's Linux runtime was having some kind of a problem with Cataclysm (all forks) when people stepped into the driver's seat of a vehicle. Investigation suggests it might be down to a problem with UTF8 stuff. This was possibly due to locale settings being iffy in Steam, so instead we switch to a decoder that doesn't depend on setlocale.
This is the test.

Possibly maybe correct a bug in the Steam Linux build

---

.github/workflows/release.yml
Makefile
src/catacharset.cpp

(pathetic groaning) attempt to fix mac and msvc builds again

Attempt to fix Mac and MSVC again

---

src/map.h
src/mapgen.cpp

Backport 75465 and 76452
More rotation fixes

Backport 75465 and 76452

---

android/app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java
android/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
android/app/src/main/java/org/libsdl/app/HIDDeviceUSB.java
android/app/src/main/java/org/libsdl/app/SDL.java
android/app/src/main/java/org/libsdl/app/SDLActivity.java
android/app/src/main/java/org/libsdl/app/SDLAudioManager.java
android/app/src/main/java/org/libsdl/app/SDLControllerManager.java
android/app/src/main/java/org/libsdl/app/SDLSurface.java
android/build_deps.sh

Backport 72154 - Update SDL version used by Android to v2.30.0

Backport 72154 - Update SDL version used by Android to v2.30.0

---

object_creator/creator_main.cpp
src/do_turn.cpp
src/flexbuffer_json.cpp
src/game.cpp
src/game.h
src/handle_action.cpp
src/init.cpp
src/input_context.cpp
src/main.cpp
src/main_menu.cpp
src/sdltiles.cpp
src/ui.cpp

Revert singint stuff
https://github.com/CleverRaven/Cataclysm-DDA/pull/78791 brought some issues to my attention. I can't directly backport it, but I can do some of the same reverts over here.
Compiles, runs, verifying screen works again, alt+f4 works again.

Revert singint stuff

---

data/json/effects_on_condition/mapgen_eocs/lab_mapgen_eocs.json
data/json/effects_on_condition/nether_eocs/vitrification_effect_on_condition.json
data/mods/TEST_DATA/effect_on_condition.json
src/condition.cpp
src/dialogue_helpers.h
src/math_parser.cpp
src/math_parser_diag.cpp
src/math_parser_diag_value.cpp
src/math_parser_diag_value.h
src/math_parser_impl.h
src/math_parser_type.h
src/npctalk.cpp
src/teleport.cpp
tests/eoc_test.cpp
tests/math_parser_test.cpp

This broke gradual mutation and I need to find out why.

Revert "Backport EOC fixes"

---

data/json/construction/floors_indoors.json
data/json/mapgen/post_office.json
src/game.cpp
src/handle_action.cpp

Fix animation options freeze
Fixes #1189 
Replace some code that accidentally got removed.
werks

Fix animation options freeze

---

data/json/effects.json
data/mods/Sky_Island/EOCs.json
data/mods/Sky_Island/dialog_statue.json
data/mods/Sky_Island/effects.json
data/mods/Sky_Island/missions_and_mapgen.json
data/mods/Sky_Island/obelisk_selector.json
data/mods/Sky_Island/sickness_checks.json
data/mods/Sky_Island/ui.json

Start fixing sky island (not fixed yet)
Sky island was broken by recent backports. I haven't figured out what exactly the cause is yet, but I can start updating the math.

Start fixing sky island (not fixed yet)

---

data/json/dreams.json
data/json/mutations/mutation_techs.json
data/json/mutations/mutations.json
data/json/npcs/campus/NPC_Elvira_Fish.json
data/json/npcs/robofac/NPC_Cranberry_Foster.json
data/json/npcs/starting_traits.json
data/json/obsoletion_and_migration/obsoletion.json
data/json/techniques.json
src/advanced_inv.cpp
src/character_body.cpp
src/npc.cpp
src/npcmove.cpp
src/npctrade.cpp
tests/reading_test.cpp

Update social and learning traits
- Truth Teller was a no brainer trait. Those are bad.
- Fast Learner was way OP and also a no brainer.
- Skilled Liar didn't really do much.
- More Psychopath interactivity was needed.
- Truth Teller is gone.
- Fast Learner is gone. If you want to learn faster, get more intelligence.
- New trait: Guileless. Guileless largely replaces Truth Teller, but with expanded functionality that made it worth making a new trait instead of fixing the old one. Guileless reduces your ability to lie and intimidate, and also makes you get worse barter prices, both as a buyer and a seller. It reduces the degree to which all NPCs fear you, and will make NPCs who are not altruistic value you less.
- Skilled Liar is now just Liar. It provides the same bonus to lying, a minor …

Update social and learning traits

---

src/weather.cpp

Fix funnels
Funnels were set up in a way that never accounted for precipitation < 1.0mm/hour. Because of this, when it was drizzling (0.5mm/hour), the one_in chance to add water to the container always evaluated to true, meaning that when it was barely raining at all, rain catchers would fill pretty much instantly, then they'd get _slower_ if it started raining harder.
Reconfigure the check slightly to account for 0.5mm precipitation.
Put a funnel up during a light drizzle. It took quite a while to even get one charge of water. Upped the rain to a storm and my rain catcher filled up pretty fast.

Fix funnels

---

data/json/mapgen/church_rural.json
data/json/mapgen_palettes/church.json
data/json/overmap/overmap_special/specials.json
data/json/overmap/overmap_terrain/overmap_terrain_public_institutional.json

Rural church updates
Rural churches were a bit too boring and safe, and had a weirdly high amount of stuff lying around.
- Reduce the amount of stuff and add a rural church variant with some danger and some environmental storytelling.

Rural church updates

---

src/animation.cpp
src/game.cpp
src/game.h
src/grab.cpp
src/handle_action.cpp
src/map.h
src/savegame.cpp

Backport 80367 - sanitize map calls

Backport 80367 - sanitize map calls
